#!/usr/bin/env node
// Generates src/generated/version.ts — run before tsc --build.
//
// The cache key is a short content hash of the sprite manifests and pixel
// hashes, not the package version. This busts precisely when the atlases
// change and stays stable when they don't, regardless of version bumps.

import { createHash } from "node:crypto";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(import.meta.url), "../../");
const DIST = join(ROOT, "dist");
const OUT = join(ROOT, "src/generated/version.ts");

const HASH_INPUTS = [
  join(DIST, "babs-de.json"),
  join(DIST, "babs-fr.json"),
  join(DIST, "babs-it.json"),
  join(ROOT, "pixels.sha256.json"),
];

const h = createHash("sha256");
for (const f of HASH_INPUTS) {
  h.update(readFileSync(f));
}
const version = h.digest("hex").slice(0, 8);

const content = `\
// GENERATED by packages/sprites/src/gen-version.ts — do not edit manually
// Content hash of babs-{de,fr,it}.json + pixels.sha256.json
export const BABS_SPRITES_VERSION = "${version}";
`;

mkdirSync(dirname(OUT), { recursive: true });

const existing = (() => {
  try {
    return readFileSync(OUT, "utf8");
  } catch {
    return null;
  }
})();
if (existing !== content) {
  writeFileSync(OUT, content, "utf8");
  console.log(`sprites/gen-version: wrote version hash ${version}`);
} else {
  console.log(`sprites/gen-version: unchanged (${version})`);
}
