version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    target-branch: "develop"
    reviewers:
      - "@f-eld-ch/Reviewers"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"       
    labels:
      - "javascript"
      - "dependencies"
    ignore:
      - dependency-name: "@types/mapbox-gl"
        versions: "> 2.x"
      - dependency-name: "@types/mapbox__mapbox-gl-draw"
        versions: "> 1.4.6"
      - dependency-name: "@types/node"
        versions: ">= 22.x, < 23"
      - dependency-name: maplibre-gl
        versions: ">= 4.a, < 5"
