// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1101: BabsIconDefinition = {
  id: "1101",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Beschaedigung", fr: "Degat", it: "Danneggiamento" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5.111 5) scale(1.07482)"><path fill="#FF0000" d="M36.3-10.9H48.3V94.6H36.3z" transform="translate(.0166 .007) rotate(-44.453 42.2925 41.8608)"/><path fill="#FF0000" d="M-11.2 36.2H94.3V48.2H-11.2z" transform="translate(.0166 .007) rotate(-44.943 41.5768 42.1986)"/></g></>
    ) }
  },
};
