// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1102: BabsIconDefinition = {
  id: "1102",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Teilzerstoerung", fr: "Destruction-partielle", it: "Distruzione-parziale" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5.9838 5) scale(1.11999)"><path fill="#FF0000" d="M44.3-10.4H49.5V75H44.3z" transform="translate(-.0314 -.0041) rotate(-44.445 46.895 32.3399)"/><path fill="#FF0000" d="M-10.6 30H74.80000000000001V35.2H-10.6z" transform="translate(-.0314 -.0041) rotate(-44.947 32.0851 32.61)"/><path fill="#FF0000" d="M3.9 45.4H89.30000000000001V50.6H3.9z" transform="translate(-.0314 -.0041) rotate(-44.947 46.6145 48.0502)"/><path fill="#FF0000" d="M30.3 5.3H35.5V90.7H30.3z" transform="translate(-.0314 -.0041) rotate(-44.445 32.9552 48.07)"/></g></>
    ) }
  },
};
