// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1103: BabsIconDefinition = {
  id: "1103",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Totalzerstoerung", fr: "Destruction-totale", it: "Distruzione-totale" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5.1705 5) scale(1.14032)"><path fill="#FF0000" d="M-8.2 24.3H61.3V29.4H-8.2z" transform="translate(.0117 .0135) rotate(-45 26.5649 26.8948)"/><path fill="#FF0000" d="M4.5 37H74V42.1H4.5z" transform="translate(.0117 .0135) rotate(-45 39.26 39.595)"/><path fill="#FF0000" d="M17.5 50H87V55.1H17.5z" transform="translate(.0117 .0135) rotate(-45 52.2298 52.555)"/><path fill="#FF0000" d="M49.5-8.4H54.6V61.1H49.5z" transform="translate(.0117 .0135) rotate(-45.008 52.0468 26.3847)"/><path fill="#FF0000" d="M36.8 4.3H41.9V73.8H36.8z" transform="translate(.0117 .0135) rotate(-45 39.3446 39.0751)"/><path fill="#FF0000" d="M23.8 17.3H28.9V86.8H23.8z" transform="translate(.0117 .0135) rotate(-45 26.385 52.0452)"/></g></>
    ) }
  },
};
