// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1104: BabsIconDefinition = {
  id: "1104",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Brand-einzelnes-Gebaeude-Flamme", fr: "Incendie-isole", it: "Incendio-di-un-singolo-edificio" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="#FD0A0A" d="M25.5 146.98c5-9.3 14-14.1 17.3-24.4 5.1-16.1 1.6-28.9-9-40.6-7.4-8.2-15.6-15.7-23-23.9-12.9-14.3-14.6-31.3-3.2-43.3C18 3.78 31.4-1.72 47.7.48c-1.7 5.2-5.4 8.6-8.4 12.2-14.2 17.1-10.7 39.3 4.9 54.6 7.2 7 14.1 14.3 20.9 21.7 17 18.9 12.8 46.3-17.5 55.6-6.8 2-13.8 4.9-22.1 2.4" transform="translate(27.1776 5) scale(.60833)"/></>
    ) }
  },
};
