// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1105b: BabsIconDefinition = {
  id: "1105b",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Explosionherd-Beispiel", fr: "Foyer-d-explosion-exemple", it: "Focolaio-esplosione-esempio" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="none" stroke="#000000" strokeDasharray="none" strokeOpacity="1" strokeWidth="1.51" d="M.95 40.58H65.53V85.12H.95z" display="inline" transform="translate(5 7.055)"/><g transform="translate(5 7.055)"><path fill="#ff0000" fillOpacity="1" fillRule="evenodd" d="m.2 64 26-10.7-19-23.5 24 14.3L18.9 4.8l18.4 27.4 4.5-32 6.7 35.4L64.4 3l-9.3 40.8 19.6-16.7L58.6 54l12.2 10Zm39.1-9.7-12.1-7.1 7.2 8.9-9.3 3.3h32.7l-5.4-4.2 3.9-6.4-8 6.9 4.1-18-5.7 11.9L42.5 28l-2.3 16.8-8.4-11.2Z" clipRule="evenodd" display="inline" transform="matrix(.75697 0 0 .75417 33.3386 .3058)"/><text x="3.32" y="81.76" fill="none" stroke="#000000" strokeDasharray="none" strokeOpacity="1" strokeWidth="1" direction="ltr" fontFamily="FreeSans" fontSize="16" fontWeight="bold" letterSpacing="0" wordSpacing="0" writingMode="lr-tb"><tspan x="3.32" y="81.76" fill="#000000" fillOpacity="1" strokeDasharray="none" strokeWidth="1" fontFamily="Open Sans" fontSize="16" fontStretch="normal" fontStyle="normal" fontVariant="normal" fontWeight="normal" letterSpacing="0">13</tspan></text></g></>
    ) }
  },
};
