// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1105a: BabsIconDefinition = {
  id: "1105a",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Explosionsherd", fr: "Foyer-d-explosion", it: "Focolaio-esplosione" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (ns: (localId: string) => string) => (
      <><g transform="translate(5 11.48) scale(1.2)"><path fill="#FFFFFF" fillOpacity="0" fillRule="evenodd" d="M0 0 75 0 75 64.2 0 64.2z" clipRule="evenodd"/><defs><path id={ns("a")} d="M.2 64 74.8 64 74.8.2.2.2z"/></defs><clipPath id={ns("b")}><use href={`#${ns("a")}`} overflow="visible"/></clipPath><g clipPath={`url(#${ns("b")})`}><path fill="#FF1415" fillRule="evenodd" d="m.2 64 26-10.7-19-23.5 24 14.3L18.9 4.8l18.4 27.4 4.5-32 6.7 35.4L64.4 3l-9.3 40.8 19.6-16.7L58.6 54l12.2 10Zm39.1-9.7-12.1-7.1 7.2 8.9-9.3 3.3h32.7l-5.4-4.2 3.9-6.4-8 6.9 4.1-18-5.7 11.9L42.5 28l-2.3 16.8-8.4-11.2Z" clipRule="evenodd"/><path fill="#FFFFFF" d="m.2 64.1 26-10.7L7.1 29.7l24 14.3L18.8 4.6l18.5 27.5 4.5-32v.2l6.7 35.4L64.5 3v.2l-9.2 40.7L74.9 27l-.1.1L58.6 54l12.2 10Zm.2-.1h70.3L58.5 54l16.1-26.8-19.5 16.7v-.1l9.2-40.5-15.9 32.4v-.1L41.8.4l-4.4 31.9v-.1L19 4.9l12.2 39.3h-.1L7.3 29.9l18.9 23.4zm57.4-4.7H24.9h.1l9.2-3.3-7.2-9 .1.1 12.1 7.1-7.6-20.8.1.1 8.4 11.2 2.3-16.9v.1l4.1 21.5 5.7-12v.2l-4.1 18 8.1-7-.1.1-3.9 6.4zm-32.6 0h32.4l-5.4-4.1 3.8-6.3-8 6.9v-.1l4-17.8-5.6 11.7v-.1l-4.1-21.4L40 44.8l-8.3-11.1 7.5 20.7-.1-.1-12-7.1 7.1 8.8z"/></g></g></>
    ) }
  },
};
