// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1301: BabsIconDefinition = {
  id: "1301",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Verletzte", fr: "Blesses", it: "Feriti" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (ns: (localId: string) => string) => (
      <><g transform="translate(5 25.52) scale(1.2)"><path fill="#FFFFFF" fillOpacity="0" fillRule="evenodd" d="M75 40.8 0 40.8 0 0 75 0z" clipRule="evenodd"/><defs><path id={ns("a")} d="M.1.1H74.89999999999999V40.7H.1z"/></defs><clipPath id={ns("b")}><use href={`#${ns("a")}`} overflow="visible"/></clipPath><g clipPath={`url(#${ns("b")})`}><path fill="#FFFFFF" fillOpacity="0" fillRule="evenodd" d="M101.6 48.5-29.4 48.5-29.4-23.2 101.6-23.2z" clipRule="evenodd"/><g enableBackground="new"><path fill="#FF0000" d="M2.7 37V3.2h11c4.2 0 6.9.2 8.1.5 1.9.5 3.6 1.6 4.9 3.3s2 3.9 2 6.6c0 2.1-.4 3.8-1.1 5.2s-1.7 2.5-2.9 3.3-2.3 1.3-3.5 1.6c-1.6.3-4 .5-7.1.5H9.6V37ZM9.6 8.9v9.6h3.7c2.7 0 4.5-.2 5.4-.5a4.7 4.7 0 0 0 2.9-4.3c0-1.2-.4-2.2-1.1-3q-1.05-1.2-2.7-1.5c-.8-.2-2.5-.3-4.9-.3ZM39.1 20l-5.9-1.1c.7-2.4 1.8-4.1 3.4-5.3 1.6-1.1 4-1.7 7.2-1.7 2.9 0 5.1.3 6.5 1s2.4 1.6 3 2.6c.6 1.1.9 3 .9 5.8l-.1 7.7c0 2.2.1 3.7.3 4.8q.3 1.5 1.2 3.3h-6.5c-.2-.4-.4-1.1-.6-1.9-.1-.4-.2-.6-.2-.8q-1.65 1.65-3.6 2.4c-1.3.5-2.6.8-4 .8q-3.75 0-6-2.1a6.7 6.7 0 0 1-2.2-5.2 6.6 6.6 0 0 1 3.8-6.2c1.2-.6 2.9-1.1 5.2-1.5 3-.6 5.1-1.1 6.3-1.6v-.6q0-1.8-.9-2.7c-.7-.5-1.8-.8-3.5-.8-1.2 0-2.1.2-2.7.7-.7.5-1.2 1.2-1.6 2.4m8.7 5.3c-.8.3-2.1.6-4 1-1.8.4-3 .8-3.5 1.1-.8.6-1.3 1.4-1.3 2.3s.3 1.7 1 2.4 1.5 1 2.6 1c1.2 0 2.3-.4 3.4-1.2q1.2-.9 1.5-2.1c.2-.6.3-1.6.3-3.2zM71.8 12.5v5.2h-4.4v9.9c0 2 0 3.2.1 3.5s.3.6.6.8.7.3 1.1.3c.6 0 1.5-.2 2.6-.6l.6 5c-1.5.6-3.2 1-5.1 1-1.3 0-2.3-.2-3.3-.6q-1.35-.6-2.1-1.5c-.5-.6-.8-1.5-.9-2.6-.1-.8-.2-2.3-.2-4.6V17.7h-3v-5.2h3V7.6l6.5-3.8v8.7z"/></g></g></g></>
    ) }
  },
};
