// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1302: BabsIconDefinition = {
  id: "1302",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Vermisste", fr: "Disparus", it: "Dispersi" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (ns: (localId: string) => string) => (
      <><g transform="translate(20.2118 5) scale(.79435)"><defs><path id={ns("a")} d="M0 0H75V113.3H0z"/></defs><clipPath id={ns("b")}><use href={`#${ns("a")}`} overflow="visible"/></clipPath><g clipPath={`url(#${ns("b")})`}><path fill="#FFFFFF" fillOpacity="0" fillRule="evenodd" d="M-5.7-4.3 80.7-4.3 80.7 116.3-5.7 116.3z" clipRule="evenodd"/><path fill="#FF0000" d="M46.4 87.8H30c0-2.4-.1-3.8-.1-4.3 0-5.3.9-9.7 2.6-13.1 1.8-3.4 5.3-7.3 10.5-11.6 5.3-4.3 8.4-7.1 9.4-8.4q2.4-3.15 2.4-6.9 0-5.25-4.2-9c-2.8-2.5-6.6-3.8-11.3-3.8-4.6 0-8.4 1.3-11.5 3.9s-5.2 6.6-6.4 11.9L5 44.6c.5-7.7 3.7-14.2 9.8-19.5s14-8 23.8-8c10.4 0 18.6 2.7 24.7 8.1s9.2 11.7 9.2 18.9c0 4-1.1 7.7-3.4 11.3-2.2 3.6-7.1 8.4-14.4 14.5-3.8 3.2-6.2 5.7-7.1 7.6s-1.3 5.4-1.2 10.3M30 112.1v-18h18v18z" enableBackground="new"/></g></g></>
    ) }
  },
};
