// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1303: BabsIconDefinition = {
  id: "1303",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Obdachlose", fr: "Sans-abri", it: "Senzatetto" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5.4786) scale(1.19236)"><path fill="#FF0000" d="M.2.2H7.6000000000000005V74.60000000000001H.2z" display="inline" transform="translate(-.0101 .0184) matrix(1 -.0051 .0051 1 -.1909 .0204)"/><path fill="#FF0000" d="M.4 67.2H75.4V74.60000000000001H.4z" display="inline" transform="translate(-.0101 .0184) rotate(-.0905 37.89 70.8815)"/><path fill="#FF0000" d="M67.9 0H75.30000000000001V74.4H67.9z" display="inline" transform="translate(-.0101 .0184) matrix(1 -.0051 .0051 1 -.1891 .3659)"/></g></>
    ) }
  },
};
