// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1305: BabsIconDefinition = {
  id: "1305",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Tote", fr: "Morts", it: "Morti" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(19.2295 5) scale(.82031)"><path fill="#FF0000" d="M33.6 0H40.800000000000004V109.7H33.6z" transform="translate(.0107 .0072) rotate(-.115 37.16 54.8491)"/><path fill="#FF0000" d="M0 35.2H75V42.400000000000006H0z" transform="translate(.0107 .0072) rotate(-.172 37.502 38.8163)"/></g></>
    ) }
  },
};
