// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs1402: BabsIconDefinition = {
  id: "1402",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Chemievergiftete Zone flüssig - sesshaft", fr: "Zone chimiquement contaminée sous forme liquide", it: "Zona intossicata liquido-persistente" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(2.7122 -.0875)"><path fill="#ffff00" fillOpacity="1" stroke="#000000" strokeWidth="3.14" d="M33.19 3.99v43a26.6 26.6 0 0 0-11.62 21.99 26.6 26.6 0 0 0 26.6 26.6 26.6 26.6 0 0 0 26.6-26.6 26.6 26.6 0 0 0-11.61-22v-43Z"/><text x="34.65" y="81.73" fill="#ffff00" fillOpacity="1" stroke="#000000" strokeWidth="1.66" direction="ltr" fontFamily="FreeSans" fontSize="37.54" fontWeight="bold" letterSpacing="-1.63" wordSpacing="0" writingMode="lr-tb"><tspan x="34.65" y="81.73" fill="#000000" fillOpacity="1" strokeWidth="1.66">C</tspan></text><path fill="#000000" stroke="#000000" strokeWidth="1.3" d="M35.61 3.76H66.14V47.07H35.61z" transform="translate(-2.7122 .0875)"/></g></>
    ) }
  },
};
