// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs2101: BabsIconDefinition = {
  id: "2101",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Chemikalien Gefahr", fr: "Danger chimique", it: "Pericolo sostanze chimiche" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 11.6359) scale(1.03687)"><path fill="#FFFFFF" d="M5.9 70.6 43.4 6.7 80.9 70.6z"/><path fill="#FF9900" d="M86.8 74H0L43.4 0Zm-75-6.8H75L43.4 13.3Z"/><path fill="#FF9900" d="m47.2 56.3 3.1 1q-.75 2.55-2.4 3.9a7 7 0 0 1-4.3 1.3c-2.1 0-3.9-.7-5.2-2.2-1.4-1.5-2.1-3.4-2.1-6 0-2.7.7-4.7 2.1-6.2s3.2-2.2 5.4-2.2c2 0 3.5.6 4.8 1.7.7.7 1.3 1.7 1.6 2.9l-3.2.8c-.2-.8-.6-1.5-1.2-2s-1.3-.7-2.2-.7c-1.2 0-2.1.4-2.9 1.3-.7.9-1.1 2.2-1.1 4.1 0 2 .4 3.5 1.1 4.3.7.9 1.7 1.3 2.8 1.3.9 0 1.6-.3 2.2-.8s1.2-1.3 1.5-2.5" enableBackground="new"/></g></>
    ) }
  },
};
