// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs2102: BabsIconDefinition = {
  id: "2102",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Elektrizität Gefahr", fr: "Danger électrique", it: "Pericolo ellettricità" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 11.6359) scale(1.03687)"><path fill="#FFFFFF" d="M43.4 6.7 80.9 70.6 5.9 70.6z"/><path fill="#FF9900" d="M86.8 74H0L43.4 0Zm-75-6.8H75L43.4 13.3Z"/><g enableBackground="new"><path fill="#FF9900" d="M34.5 62.2v-16h11.9v2.7h-8.6v3.5h8v2.7h-8v4.4h8.9v2.7zM49.4 62.2v-16h3.1v16z"/></g></g></>
    ) }
  },
};
