// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs2104: BabsIconDefinition = {
  id: "2104",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Gas Gefahr", fr: "Danger de gaz", it: "Pericolo gas" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 11.6359) scale(1.03687)"><path fill="#FFFFFF" d="M5.9 70.6 43.4 6.7 80.9 70.6z"/><path fill="#FF9900" d="M86.8 74H0L43.4 0Zm-75-6.8H75L43.4 13.3Z"/><path fill="#FF9900" d="M43.8 56.3v-2.7h7V60c-.7.7-1.7 1.2-2.9 1.7-1.3.5-2.6.7-3.9.7-1.7 0-3.1-.4-4.4-1.1-1.2-.7-2.2-1.7-2.8-3s-.9-2.7-.9-4.3c0-1.7.3-3.1 1-4.4s1.7-2.3 3.1-3c1-.5 2.3-.8 3.8-.8 2 0 3.5.4 4.7 1.3s1.8 2 2.2 3.5l-3.2.6c-.2-.8-.7-1.4-1.3-1.9s-1.4-.7-2.3-.7c-1.4 0-2.5.4-3.4 1.3-.8.9-1.3 2.2-1.3 4 0 1.9.4 3.3 1.3 4.3s2 1.4 3.3 1.4c.7 0 1.4-.1 2-.4.7-.3 1.3-.6 1.8-1v-2h-3.8z" enableBackground="new"/></g></>
    ) }
  },
};
