// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs2105: BabsIconDefinition = {
  id: "2105",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Unfall Gefahr", fr: "Danger d'accident", it: "Pericolo Incidente" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 11.564) scale(1.2)"><path fill="#fff" strokeWidth="0" d="M37.46 4.57 5.7 61.54 69.22 61.54z"/><path fill="#fff" strokeWidth="0" d="M70.13 62.08H4.79L37.46 3.47ZM6.61 61.01h61.7L37.46 5.67Z"/><path fill="#f90" fillRule="evenodd" strokeWidth="0" d="M74.9 63.96H.1L37.5.1zm-9.41-4.66L37.5 10.96l-28 48.35h56z"/><path fill="#f90" strokeWidth="0" d="M31.95 38.47h2.8v7.49q0 1.78.1 2.31.18.85.86 1.36t1.85.51q1.19 0 1.8-.49.6-.48.73-1.19.12-.7.12-2.35v-7.65h2.8v7.27q0 2.49-.23 3.52a4 4 0 0 1-.84 1.74q-.61.7-1.63 1.13t-2.67.42a8 8 0 0 1-3.02-.46 4.1 4.1 0 0 1-2.41-2.72q-.27-1.19-.27-3.51v-7.38z"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 11.378) scale(1.2)"><g transform="translate(-258.74 -387.49)"><path fill="#FFFFFF" d="M296.73 397.21 311.41 423.03 326.09 448.84 296.96 448.33 267.82 447.81 282.27 422.51z"/><path fill="#FFFFFF" d="m326.4 449.02-.31-.01-58.57-1.03 29.21-51.13.15.27zm-58.28-1.37 57.67 1.02-29.06-51.1z"/></g><g transform="translate(-258.74 -387.49)"><path fill="#FF9900" fillRule="evenodd" d="M333.65 451.77h-74.81l37.4-64.18zm-9.41-4.68-28-48.58-28 48.58z" clipRule="evenodd"/><path fill="#FF9900" d="M292.2 440.04h-3.06l-1.21-3.16h-5.56l-1.15 3.16h-2.98l5.42-13.9h2.97zm-5.17-5.49-1.92-5.16-1.88 5.16zM302.42 432.95l-2.63.47a2 2 0 0 0-.6-1.18 1.8 1.8 0 0 0-1.22-.4 2 2 0 0 0-1.59.69q-.6.69-.59 2.3 0 1.79.6 2.53t1.62.74q.76 0 1.24-.43t.68-1.48l2.62.45a4.6 4.6 0 0 1-1.57 2.72q-1.15.92-3.1.92a4.6 4.6 0 0 1-3.52-1.39 5.4 5.4 0 0 1-1.31-3.86q0-2.5 1.32-3.88a4.7 4.7 0 0 1 3.57-1.39q1.84 0 2.93.79a4.3 4.3 0 0 1 1.55 2.4M313.21 432.95l-2.63.47a2 2 0 0 0-.6-1.18 1.8 1.8 0 0 0-1.22-.4 2 2 0 0 0-1.59.69q-.6.69-.59 2.3 0 1.79.6 2.53t1.62.74q.76 0 1.24-.43t.68-1.48l2.62.45a4.6 4.6 0 0 1-1.57 2.72q-1.16.92-3.1.92a4.6 4.6 0 0 1-3.52-1.39 5.4 5.4 0 0 1-1.31-3.86q0-2.5 1.32-3.88a4.7 4.7 0 0 1 3.57-1.39q1.84 0 2.93.79a4.3 4.3 0 0 1 1.55 2.4"/></g></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 10.6834) scale(.41713)"><g transform="translate(-187.62 -326.88)"><path fill="#FFFFFF" d="M297.2 342.44 198.65 507.09 395.75 507.09z"/><path fill="#FFFFFF" d="M397.72 508.21H196.68L297.2 340.26Zm-197.1-2.23h193.16L297.2 344.61Z"/></g><g transform="translate(-187.62 -326.88)"><path fill="#FF9900" fillRule="evenodd" d="M403.1 511.55H187.9l107.6-184.67Zm-27.05-13.47L295.5 358.29l-80.55 139.79Z" clipRule="evenodd"/><path fill="#FF9900" d="M279.33 435.72h8.13v21.86q0 5.2.3 6.74a6.6 6.6 0 0 0 2.49 3.98q1.97 1.5 5.37 1.5 3.46 0 5.22-1.42a5.7 5.7 0 0 0 2.12-3.48q.36-2.07.36-6.85v-22.32h8.13v21.19q0 7.26-.66 10.27t-2.43 5.06a12.4 12.4 0 0 1-4.74 3.29q-2.97 1.23-7.75 1.23-5.77 0-8.75-1.33a12.5 12.5 0 0 1-4.71-3.47 11 11 0 0 1-2.28-4.47q-.8-3.47-.8-10.24z"/></g></g></>
    ) }
  },
};
