// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs2106: BabsIconDefinition = {
  id: "2106",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Gefahr durch Löschen mit Wasser", fr: "Danger-si-extinction-avec-eau", it: "Pericolo in caso di spegnimento con acqua" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 11.6359) scale(1.03687)"><path fill="#FFFFFF" d="M43.4 6.7 80.9 70.6 5.9 70.6z"/><path fill="#FF9900" d="M86.8 74H0L43.4 0Zm-75-6.8H75L43.4 13.3Z"/><path fill="#FF9900" d="M42 33.7H44.8V67.2H42z" transform="rotate(-44.984 43.3893 50.4622)"/><path fill="#FF9900" d="M26.7 49.1H60.2V51.9H26.7z" transform="rotate(-45.016 43.3824 50.4586)"/><path fill="#FF9900" d="M49.6 58.3c0 .2-.1.3-.2.4s-.2.2-.3.2c-.2.1-.3.1-.6.1h-1.9c-.2 0-.4-.1-.6-.1-.1-.1-.2-.1-.3-.2s-.1-.2-.2-.4l-2.2-8.9-2.1 8.9c0 .2-.1.3-.2.4s-.2.2-.3.2c-.1.1-.3.1-.6.1h-2c-.2 0-.4-.1-.6-.1-.1-.1-.2-.1-.3-.2s-.1-.2-.2-.4l-3.2-12.2c-.1-.3-.1-.5-.1-.6s0-.3.1-.3c.1-.1.2-.1.4-.1h1.7c.2 0 .3 0 .4.1s.2.1.2.2.1.2.1.3l2.5 10.7 2.6-10.7c0-.1.1-.2.1-.3s.1-.2.2-.2.3-.1.5-.1h1.6c.2 0 .4 0 .5.1s.2.1.2.2c.1.1.1.2.1.3l2.6 10.7L50 45.7c0-.1 0-.2.1-.3 0-.1.1-.1.2-.2.1 0 .2-.1.4-.1h1.5c.2 0 .3.1.4.1.1.1.1.2.1.4s0 .4-.1.6z" enableBackground="new"/></g></>
    ) }
  },
};
