// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs2108: BabsIconDefinition = {
  id: "2108",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Gefahr für Grundwasser", fr: "Danger-pour-les-eaux de surface", it: "Pericolo per le acque in superficie" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 11.6359) scale(1.03687)"><path fill="#FFFFFF" d="M5.9 70.6 43.4 6.7 80.9 70.6z"/><path fill="#FF9900" d="M86.8 74H0L43.4 0Zm-75-6.8H75L43.4 13.3Z"/><path fill="#FF9415" fillRule="evenodd" d="m49.4 42.1-6 10.3-6-10.3h4.4V24.8h3v17.3zm13.2 14.6c-3.2-.1-4 2.3-4 5-.5 1.5-2.5 1.8-3.7 1.1-1.7-1.1-.3-4-2.1-5.2-1.5-1.2-3.7-1.1-5.3-.5-2.5 1.4-.9 4-2.4 5.6-.9.6-2.2.6-3.2.1-1.5-1.2-.3-3.7-1.9-5-1.4-1.3-4-1.4-5.6-.5-2.5 1.2-.5 5-3 5.8-1.6.5-3.5-.4-3.3-2.3.3-3.6-3.6-4.9-6.5-3.6-1.3.7-1.8 2.1-1.7 3.5.4-.1 1.9.3 1.8-.4-.1-1.8 2.3-2.4 3.5-1.3 1.3 1.1 1.1 3.1 2.1 4.4 1.5 1.8 4.6 1.8 6.2.3 1.3-1.3.2-3.7 1.6-4.7 1-.8 2.6-.6 3.5.1 1 1.1.3 2.8 1.1 4.1 1.3 2.1 4.9 2.2 6.7.5 1.2-1.2.5-3.2 1.3-4.5 1.1-1.1 3.3-1 4.2.3.4.7.3 1.7.4 2.5.3 1.8 2 2.8 3.8 2.7 1.7.2 3.8-.7 4-2.7.3-.8 0-1.8.5-2.7.8-1.3 3.1-1.3 4.1-.3.9 1.6-.1 1.6 2.2 1.5.1-2.4-1.9-3.9-4.3-3.8" clipRule="evenodd"/></g></>
    ) }
  },
};
