// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs2109b: BabsIconDefinition = {
  id: "2109b",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Gefahrentafel mit UN-Nummer", fr: "Plaque de danger avec numéro ONU", it: "Pannello di pericolo con numero ONU" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="#ffffff" strokeWidth="0" d="M6.12 22.48H93.43V78.47H6.12z"/><path fill="none" stroke="#ff9900" strokeDasharray="none" strokeOpacity="1" strokeWidth="29.13" d="M12.27 239.9h720.82M11.1 12.29h725.37v458.16H11.09Z" transform="translate(5 21.0414) scale(.12016)"/><text x="380.63" y="201.32" fill="none" stroke="#ff9900" strokeDasharray="none" strokeOpacity="1" strokeWidth="0" direction="ltr" fontFamily="FreeSans" fontSize="221.93" fontWeight="bold" letterSpacing="-10.57" style={{ textAlign: "center" }} textAnchor="middle" transform="translate(5 21.0414)scale(.12016)" wordSpacing="0" writingMode="lr-tb"><tspan x="375.34" y="201.32" fill="#ff9900" fillOpacity="1" strokeDasharray="none" strokeWidth="0" fontSize="221.93">80</tspan></text><text x="368.03" y="432.75" fill="none" stroke="#ff9900" strokeDasharray="none" strokeOpacity="1" strokeWidth="0" direction="ltr" fontFamily="FreeSans" fontSize="221.93" fontWeight="bold" letterSpacing="-10.57" style={{ textAlign: "center" }} textAnchor="middle" transform="translate(5 21.0414)scale(.12016)" wordSpacing="0" writingMode="lr-tb"><tspan x="362.75" y="432.75" fill="#ff9900" fillOpacity="1" strokeDasharray="none" strokeWidth="0" fontSize="221.93">1789</tspan></text></>
    ) }
  },
};
