// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs2109a: BabsIconDefinition = {
  id: "2109a",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Gefahrentafel ohne UN-Nummer", fr: "Plaque de danger sans numéro ONU", it: "Pannello di pericolo senza numero ONU" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="none" stroke="#ff9900" strokeDasharray="none" strokeOpacity="1" strokeWidth="29.13" d="M12.27 239.9h720.82M11.1 12.29h725.37v458.16H11.09Z" transform="translate(5 21.0414) scale(.12016)"/></>
    ) }
  },
};
