// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs3103: BabsIconDefinition = {
  id: "3103",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Kommandoposten Front", fr: "PC engagement", it: "Posto di comando fronte" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(22.1617 5) scale(.69752) translate(.0105)"><path fill="blue" strokeWidth="0" d="M11.17 33.33H16.8V114.16H11.17z" display="inline"/><path fill="blue" strokeWidth="0" d="M45.49 66.27c-18.92 0-34.32-14.86-34.32-33.13S26.56 0 45.49 0s34.32 14.86 34.32 33.13-15.4 33.14-34.32 33.14m0-60.64c-15.82 0-28.69 12.34-28.69 27.51s12.87 27.51 28.69 27.51 28.69-12.34 28.69-27.51S61.31 5.63 45.49 5.63" display="inline"/><path fill="blue" strokeWidth="0" d="M39.91 41.8V25.1h11.46v2.82h-8.09v3.95h6.98v2.82h-6.98v7.1z" display="inline"/><path fill="#fff" strokeWidth="0" d="M2.71 102.97 26.69 127.02"/><path fill="blue" strokeWidth="0" d="M11.88 98.02H17.51V131.98H11.88z" transform="rotate(-44.92 14.7023 114.9972)"/><path fill="#fff" strokeWidth="0" d="M25.96 102.96 1.99 127.04" display="inline"/><path fill="blue" strokeWidth="0" d="M-3.01 112.18H30.97V117.81H-3.01z" display="inline" transform="rotate(-45.13 13.983 115.009)"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(22.2248 5) scale(.71125)"><path fill="#FFFFFF" d="M303.96 388.7c-18.07 0-32.77-14.29-32.77-31.86s14.7-31.86 32.77-31.86 32.76 14.29 32.76 31.86-14.69 31.86-32.76 31.86m0-62.85c-17.59 0-31.89 13.9-31.89 30.99s14.31 30.99 31.89 30.99c17.59 0 31.89-13.9 31.89-30.99s-14.3-30.99-31.89-30.99" transform="translate(-259.347 -324.51)"/><g transform="translate(-259.347 -324.51)"><path fill="#FFFFFF" d="M273.09 357.62 273.09 434.7"/><path fill="#0000FF" d="M270.35 357.62H275.84000000000003V434.7H270.35z"/><path fill="#0000FF" d="M303.96 389.17c-18.46 0-33.49-14.5-33.49-32.33s15.02-32.33 33.49-32.33 33.49 14.5 33.49 32.33-15.02 32.33-33.49 32.33m0-59.17c-15.44 0-28 12.04-28 26.84s12.56 26.84 28 26.84 28-12.04 28-26.84-12.56-26.84-28-26.84"/><path fill="#0000FF" d="M282.03 365.87v-16.29h5.29q3 0 3.92.24 1.4.37 2.35 1.59t.95 3.17q0 1.5-.55 2.52a4.6 4.6 0 0 1-3.1 2.38q-1.19.24-3.42.23h-2.15v6.15h-3.29zm3.3-13.53v4.62h1.8q1.95 0 2.6-.26a2.3 2.3 0 0 0 1.03-.8q.37-.55.37-1.27 0-.88-.52-1.47a2.2 2.2 0 0 0-1.32-.72q-.58-.1-2.37-.11zM307.68 359.88l3.2 1.01a7 7 0 0 1-2.44 3.96 7 7 0 0 1-4.34 1.29 7 7 0 0 1-5.34-2.22q-2.09-2.22-2.09-6.06 0-4.07 2.1-6.32a7.2 7.2 0 0 1 5.53-2.25q3 0 4.86 1.77 1.11 1.05 1.67 3l-3.26.78a3.5 3.5 0 0 0-1.21-2 3.5 3.5 0 0 0-2.23-.73 3.7 3.7 0 0 0-2.94 1.3q-1.13 1.3-1.13 4.21 0 3.1 1.11 4.4a3.6 3.6 0 0 0 2.89 1.31q1.32 0 2.26-.83a5 5 0 0 0 1.36-2.62M313.7 365.87v-16.29h12.1v2.76H317v3.61h8.19v2.74H317v4.43h9.12v2.74z"/><path fill="#FFFFFF" d="M261.29 425.56 284.69 449.02"/><path fill="#0000FF" d="M270.25 420.73H275.74V453.86H270.25z" transform="rotate(-44.919 273.008 437.3052)"/><path fill="#FFFFFF" d="M284.69 425.62 261.3 449.11"/><path fill="#0000FF" d="M256.42 434.62H289.57V440.11H256.42z" transform="rotate(-45.13 272.997 437.364)"/></g></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(22.1802 5) scale(.49028) translate(-241.6434 -296.67)"><path fill="#FFFFFF" d="M261.53 344.06 261.53 458.32"/><path fill="#0000FF" d="M257.53 344.06H265.53V458.32H257.53z"/><path fill="#0000FF" d="M306.33 390.89c-26.91 0-48.8-21.13-48.8-47.11s21.89-47.11 48.8-47.11 48.8 21.13 48.8 47.11c0 25.97-21.89 47.11-48.8 47.11m0-86.23c-22.5 0-40.8 17.55-40.8 39.11 0 21.57 18.3 39.11 40.8 39.11s40.8-17.55 40.8-39.11-18.3-39.11-40.8-39.11"/><path fill="#0000FF" d="M298.4 356.09v-23.74h16.3v4.02h-11.5v5.62h9.93v4.02h-9.93v10.09z"/><path fill="#FFFFFF" d="M244.48 443.12 278.58 477.3"/><path fill="#0000FF" d="M257.53 436.07H265.53V484.35H257.53z" transform="rotate(-44.919 261.5486 460.2241)"/><path fill="#FFFFFF" d="M278.58 443.19 244.49 477.43"/><path fill="#0000FF" d="M237.38 456.31H285.69V464.31H237.38z" transform="rotate(-45.13 261.5252 460.3028)"/></g></>
    ) }
  },
};
