// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4305: BabsIconDefinition = {
  id: "4305",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Bataillon-San", fr: "Bataillon-San", it: "Bataillone-San" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><defs><path d="M22.9 40.25H78.36V77.55H22.9z"/></defs><g transform="translate(19.7774 5) scale(14.3214) translate(-39.044 -21.3157)scale(.04688)"><text x="27.73" y="0" fill="#0000ff" direction="ltr" display="inline" fontFamily="FreeSans" fontSize="26.67" fontWeight="bold" letterSpacing="-1.58" style={{ textAlign: "center", whiteSpace: "pre" }} transform="translate(802.2548 460.8467)scale(1.48961)" wordSpacing="0" writingMode="lr-tb"><tspan x="27.41" y="64.92">San</tspan></text><path fill="#0000FF" d="M877.96 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.2 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89" display="inline"/><g display="inline"><path fill="#FFFFFF" d="M877.86 502.84 878.06 454.75"/><path fill="#0000FF" d="M853.91 474.3H901.99V483.3H853.91z" transform="rotate(-89.7575 877.956 478.7957)"/></g><g display="inline"><path fill="#FFFFFF" d="M899.48 481.03 856.43 481.03"/><path fill="#0000FF" d="M856.43 476.53H899.4799999999999V485.53H856.43z"/></g><g display="inline"><path fill="#FFFFFF" d="M899.48 468.08 856.43 468.08"/><path fill="#0000FF" d="M856.43 463.58H899.4799999999999V472.58H856.43z"/></g></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><defs><path d="M22.9 40.25H78.36V77.55H22.9z"/></defs><g transform="translate(19.7774 5) scale(14.3214) translate(-39.044 -21.3157)scale(.04688)"><text x="27.73" y="0" fill="#0000ff" direction="ltr" display="inline" fontFamily="FreeSans" fontSize="26.67" fontWeight="bold" letterSpacing="-1.58" style={{ textAlign: "center", whiteSpace: "pre" }} transform="translate(802.2548 460.8467)scale(1.48961)" wordSpacing="0" writingMode="lr-tb"><tspan x="27.41" y="64.92">San</tspan></text><path fill="#0000FF" d="M877.96 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.2 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89" display="inline"/><g display="inline"><path fill="#FFFFFF" d="M877.86 502.84 878.06 454.75"/><path fill="#0000FF" d="M853.91 474.3H901.99V483.3H853.91z" transform="rotate(-89.7575 877.956 478.7957)"/></g><g display="inline"><path fill="#FFFFFF" d="M899.48 481.03 856.43 481.03"/><path fill="#0000FF" d="M856.43 476.53H899.4799999999999V485.53H856.43z"/></g><g display="inline"><path fill="#FFFFFF" d="M899.48 468.08 856.43 468.08"/><path fill="#0000FF" d="M856.43 463.58H899.4799999999999V472.58H856.43z"/></g></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><defs><path d="M22.9 40.25H78.36V77.55H22.9z"/></defs><g transform="translate(19.7774 5) scale(14.3214) translate(-39.044 -21.3157)scale(.04688)"><text x="27.73" y="0" fill="#0000ff" direction="ltr" display="inline" fontFamily="FreeSans" fontSize="26.67" fontWeight="bold" letterSpacing="-1.58" style={{ textAlign: "center", whiteSpace: "pre" }} transform="translate(802.2548 460.8467)scale(1.48961)" wordSpacing="0" writingMode="lr-tb"><tspan x="27.41" y="64.92">San</tspan></text><path fill="#0000FF" d="M877.96 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.2 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89" display="inline"/><g display="inline"><path fill="#FFFFFF" d="M877.86 502.84 878.06 454.75"/><path fill="#0000FF" d="M853.91 474.3H901.99V483.3H853.91z" transform="rotate(-89.7575 877.956 478.7957)"/></g><g display="inline"><path fill="#FFFFFF" d="M899.48 481.03 856.43 481.03"/><path fill="#0000FF" d="M856.43 476.53H899.4799999999999V485.53H856.43z"/></g><g display="inline"><path fill="#FFFFFF" d="M899.48 468.08 856.43 468.08"/><path fill="#0000FF" d="M856.43 463.58H899.4799999999999V472.58H856.43z"/></g></g></>
    ) }
  },
};
