// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4402: BabsIconDefinition = {
  id: "4402",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Gruppe-ZS", fr: "Groupe-PCi", it: "Gruppo-PCi" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><defs><path d="M22.9 40.25H78.36V77.55H22.9z"/><path d="M22.9 40.25H78.36V77.55H22.9z"/></defs><g transform="translate(14.2453 5) scale(1.73332) translate(-28.529 -13.6159)scale(.45356)"><circle cx="90.05" cy="41.95" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M90.05 53.88a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.84a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/><circle cx="126.71" cy="41.95" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M126.71 53.88a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.84a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82M108.38 144.5c-25.08 0-45.48-20.32-45.48-45.29s20.4-45.29 45.48-45.29 45.48 20.32 45.48 45.29-20.4 45.29-45.48 45.29m0-80.58c-19.56 0-35.48 15.83-35.48 35.29s15.92 35.29 35.48 35.29 35.48-15.83 35.48-35.29-15.92-35.29-35.48-35.29"/><text x="27.73" y="0" fill="#0000ff" direction="ltr" display="inline" fontFamily="FreeSans" fontSize="26.67" fontWeight="bold" letterSpacing="-.4" style={{ textAlign: "center", whiteSpace: "pre" }} transform="translate(45.3271 28.7538)scale(1.272)" wordSpacing="0" writingMode="lr-tb"><tspan x="33.64" y="64.92">ZS</tspan></text></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><defs><path d="M22.9 40.25H78.36V77.55H22.9z"/><path d="M22.9 40.25H78.36V77.55H22.9z"/></defs><g transform="translate(14.2453 5) scale(1.73332) translate(-28.529 -13.6159)scale(.45356)"><circle cx="90.05" cy="41.95" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M90.05 53.88a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.84a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/><circle cx="126.71" cy="41.95" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M126.71 53.88a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.84a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82M108.38 144.5c-25.08 0-45.48-20.32-45.48-45.29s20.4-45.29 45.48-45.29 45.48 20.32 45.48 45.29-20.4 45.29-45.48 45.29m0-80.58c-19.56 0-35.48 15.83-35.48 35.29s15.92 35.29 35.48 35.29 35.48-15.83 35.48-35.29-15.92-35.29-35.48-35.29"/><text x="27.73" y="0" fill="#0000ff" direction="ltr" display="inline" fontFamily="FreeSans" fontSize="26.67" fontWeight="bold" letterSpacing="-.4" style={{ textAlign: "center", whiteSpace: "pre" }} transform="translate(45.3271 28.7538)scale(1.272)" wordSpacing="0" writingMode="lr-tb"><tspan x="28.65" y="64.92">PCi</tspan></text></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><defs><path d="M22.9 40.25H78.36V77.55H22.9z"/><path d="M22.9 40.25H78.36V77.55H22.9z"/></defs><g transform="translate(14.2453 5) scale(1.73332) translate(-28.529 -13.6159)scale(.45356)"><circle cx="90.05" cy="41.95" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M90.05 53.88a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.84a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/><circle cx="126.71" cy="41.95" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M126.71 53.88a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.84a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82M108.38 144.5c-25.08 0-45.48-20.32-45.48-45.29s20.4-45.29 45.48-45.29 45.48 20.32 45.48 45.29-20.4 45.29-45.48 45.29m0-80.58c-19.56 0-35.48 15.83-35.48 35.29s15.92 35.29 35.48 35.29 35.48-15.83 35.48-35.29-15.92-35.29-35.48-35.29"/><text x="27.73" y="0" fill="#0000ff" direction="ltr" display="inline" fontFamily="FreeSans" fontSize="26.67" fontWeight="bold" letterSpacing="-.4" style={{ textAlign: "center", whiteSpace: "pre" }} transform="translate(45.3271 28.7538)scale(1.272)" wordSpacing="0" writingMode="lr-tb"><tspan x="28.65" y="64.92">PCi</tspan></text></g></>
    ) }
  },
};
