// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4601: BabsIconDefinition = {
  id: "4601",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Trupp-A", fr: "Equipe-A", it: "Squadra-Es" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><defs><path d="M22.9 40.25H78.36V77.55H22.9z"/><path d="M31.31 44.9H67.53999999999999V76.65H31.31z"/></defs><g transform="translate(15.1465 5) scale(1.68963) translate(-24.3698 -12.2733)scale(.45356)"><circle cx="99.21" cy="38.99" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M99.21 50.92a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.85a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/><path fill="#0000FF" d="M99.21 144.5c-25.08 0-45.48-20.32-45.48-45.29s20.4-45.29 45.48-45.29 45.48 20.32 45.48 45.29-20.4 45.29-45.48 45.29m0-80.58c-19.56 0-35.48 15.83-35.48 35.29s15.92 35.29 35.48 35.29 35.48-15.83 35.48-35.29-15.91-35.29-35.48-35.29" display="inline"/><text x="27.73" y="0" fill="#0000ff" direction="ltr" display="inline" fontFamily="FreeSans" fontSize="26.67" fontWeight="bold" letterSpacing="-.4" style={{ textAlign: "center", whiteSpace: "pre" }} transform="translate(33.8488 27.1884)scale(1.30489)" wordSpacing="0" writingMode="lr-tb"><tspan x="41.33" y="64.92">A</tspan></text></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><defs><path d="M22.9 40.25H78.36V77.55H22.9z"/><path d="M31.31 44.9H67.53999999999999V76.65H31.31z"/></defs><g transform="translate(15.1465 5) scale(1.68963) translate(-24.3698 -12.2733)scale(.45356)"><circle cx="99.21" cy="38.99" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M99.21 50.92a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.85a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/><path fill="#0000FF" d="M99.21 144.5c-25.08 0-45.48-20.32-45.48-45.29s20.4-45.29 45.48-45.29 45.48 20.32 45.48 45.29-20.4 45.29-45.48 45.29m0-80.58c-19.56 0-35.48 15.83-35.48 35.29s15.92 35.29 35.48 35.29 35.48-15.83 35.48-35.29-15.91-35.29-35.48-35.29" display="inline"/><text x="27.73" y="0" fill="#0000ff" direction="ltr" display="inline" fontFamily="FreeSans" fontSize="26.67" fontWeight="bold" letterSpacing="-.4" style={{ textAlign: "center", whiteSpace: "pre" }} transform="translate(33.8488 27.1884)scale(1.30489)" wordSpacing="0" writingMode="lr-tb"><tspan x="41.33" y="64.92">A</tspan></text></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><defs><path d="M22.9 40.25H78.36V77.55H22.9z"/><path d="M31.31 44.9H67.53999999999999V76.65H31.31z"/></defs><g transform="translate(15.1465 5) scale(1.68963) translate(-24.3698 -12.2733)scale(.45356)"><circle cx="99.21" cy="38.99" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M99.21 50.92a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.85a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/><path fill="#0000FF" d="M99.21 144.5c-25.08 0-45.48-20.32-45.48-45.29s20.4-45.29 45.48-45.29 45.48 20.32 45.48 45.29-20.4 45.29-45.48 45.29m0-80.58c-19.56 0-35.48 15.83-35.48 35.29s15.92 35.29 35.48 35.29 35.48-15.83 35.48-35.29-15.91-35.29-35.48-35.29" display="inline"/><text x="27.73" y="0" fill="#0000ff" direction="ltr" display="inline" fontFamily="FreeSans" fontSize="26.67" fontWeight="bold" letterSpacing="-.4" style={{ textAlign: "center", whiteSpace: "pre" }} transform="translate(33.8488 27.1884)scale(1.30489)" wordSpacing="0" writingMode="lr-tb"><tspan x="34.55" y="64.92">Es</tspan></text></g></>
    ) }
  },
};
