// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4704: BabsIconDefinition = {
  id: "4704",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "ZS", fr: "PCi", it: "PCi" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5) scale(22.7542) translate(-39.249 -23.5181)scale(.04688)"><path fill="#0000FF" d="M879.5 586.1a42.24 42.24 0 0 1-42.19-42.19 42.24 42.24 0 0 1 42.19-42.19 42.24 42.24 0 0 1 42.19 42.19 42.23 42.23 0 0 1-42.19 42.19m0-75a32.85 32.85 0 0 0-32.81 32.81 32.85 32.85 0 0 0 32.81 32.81 32.85 32.85 0 0 0 32.81-32.81 32.85 32.85 0 0 0-32.81-32.81"/><text x="879.95" y="557.24" fill="#0000ff" strokeWidth=".94" direction="ltr" fontFamily="FreeSans" fontSize="37.5" fontWeight="bold" letterSpacing="-1.48" style={{ textAlign: "center" }} textAnchor="middle" wordSpacing="0" writingMode="lr-tb"><tspan x="879.21" y="557.24" strokeWidth=".94" fontSize="37.5">ZS</tspan></text></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5) scale(22.7542) translate(-39.249 -23.5181)scale(.04688)"><path fill="#0000FF" d="M879.5 586.1a42.24 42.24 0 0 1-42.19-42.19 42.24 42.24 0 0 1 42.19-42.19 42.24 42.24 0 0 1 42.19 42.19 42.23 42.23 0 0 1-42.19 42.19m0-75a32.85 32.85 0 0 0-32.81 32.81 32.85 32.85 0 0 0 32.81 32.81 32.85 32.85 0 0 0 32.81-32.81 32.85 32.85 0 0 0-32.81-32.81"/><text x="879.95" y="557.24" fill="#0000ff" strokeWidth=".94" direction="ltr" fontFamily="FreeSans" fontSize="37.5" fontWeight="bold" letterSpacing="-1.48" style={{ textAlign: "center" }} textAnchor="middle" wordSpacing="0" writingMode="lr-tb"><tspan x="879.21" y="557.24" strokeWidth=".94" fontSize="37.5">PCi</tspan></text></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5) scale(22.7542) translate(-39.249 -23.5181)scale(.04688)"><path fill="#0000FF" d="M879.5 586.1a42.24 42.24 0 0 1-42.19-42.19 42.24 42.24 0 0 1 42.19-42.19 42.24 42.24 0 0 1 42.19 42.19 42.23 42.23 0 0 1-42.19 42.19m0-75a32.85 32.85 0 0 0-32.81 32.81 32.85 32.85 0 0 0 32.81 32.81 32.85 32.85 0 0 0 32.81-32.81 32.85 32.85 0 0 0-32.81-32.81"/><text x="879.95" y="557.24" fill="#0000ff" strokeWidth=".94" direction="ltr" fontFamily="FreeSans" fontSize="37.5" fontWeight="bold" letterSpacing="-1.48" style={{ textAlign: "center" }} textAnchor="middle" wordSpacing="0" writingMode="lr-tb"><tspan x="879.21" y="557.24" strokeWidth=".94" fontSize="37.5">PCi</tspan></text></g></>
    ) }
  },
};
