// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4705: BabsIconDefinition = {
  id: "4705",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "TechnB", fr: "S tec", it: "S tec" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5) scale(22.7542) translate(-39.249 -23.5181)scale(.04688)"><path fill="#0000FF" d="M879.5 586.1a42.24 42.24 0 0 1-42.19-42.19 42.24 42.24 0 0 1 42.19-42.19 42.24 42.24 0 0 1 42.19 42.19 42.23 42.23 0 0 1-42.19 42.19m0-75a32.85 32.85 0 0 0-32.81 32.81 32.85 32.85 0 0 0 32.81 32.81 32.85 32.85 0 0 0 32.81-32.81 32.85 32.85 0 0 0-32.81-32.81" display="inline"/><text x="849.23" y="548.02" fill="#0000ff" strokeWidth=".94" direction="ltr" fontFamily="FreeSans" fontSize="22.5" fontWeight="bold" letterSpacing="-1.48" wordSpacing="0" writingMode="lr-tb"><tspan x="849.23" y="548.02" strokeWidth=".94" fontSize="22.5">Techn</tspan></text><text x="872.79" y="567.47" fill="#0000ff" strokeWidth=".94" direction="ltr" fontFamily="FreeSans" fontSize="22.5" fontWeight="bold" letterSpacing="-1.48" wordSpacing="0" writingMode="lr-tb"><tspan x="872.79" y="567.47" strokeWidth=".94">B</tspan></text></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5) scale(22.7542) translate(-39.249 -23.5181)scale(.04688)"><path fill="#0000FF" d="M879.5 586.1a42.24 42.24 0 0 1-42.19-42.19 42.24 42.24 0 0 1 42.19-42.19 42.24 42.24 0 0 1 42.19 42.19 42.23 42.23 0 0 1-42.19 42.19m0-75a32.85 32.85 0 0 0-32.81 32.81 32.85 32.85 0 0 0 32.81 32.81 32.85 32.85 0 0 0 32.81-32.81 32.85 32.85 0 0 0-32.81-32.81" display="inline"/><text x="849.23" y="548.02" fill="#0000ff" strokeWidth=".94" direction="ltr" fontFamily="FreeSans" fontSize="36" fontWeight="bold" letterSpacing="-1.48" wordSpacing="0" writingMode="lr-tb"><tspan x="849.23" y="548.02" strokeWidth=".94" fontSize="28">S tec</tspan></text></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5) scale(22.7542) translate(-39.249 -23.5181)scale(.04688)"><path fill="#0000FF" d="M879.5 586.1a42.24 42.24 0 0 1-42.19-42.19 42.24 42.24 0 0 1 42.19-42.19 42.24 42.24 0 0 1 42.19 42.19 42.23 42.23 0 0 1-42.19 42.19m0-75a32.85 32.85 0 0 0-32.81 32.81 32.85 32.85 0 0 0 32.81 32.81 32.85 32.85 0 0 0 32.81-32.81 32.85 32.85 0 0 0-32.81-32.81" display="inline"/><text x="849.23" y="548.02" fill="#0000ff" strokeWidth=".94" direction="ltr" fontFamily="FreeSans" fontSize="36" fontWeight="bold" letterSpacing="-1.48" wordSpacing="0" writingMode="lr-tb"><tspan x="849.23" y="548.02" strokeWidth=".94" fontSize="28">S tec</tspan></text></g></>
    ) }
  },
};
