// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4706: BabsIconDefinition = {
  id: "4706",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "A", fr: "A", it: "Es" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5.1299) scale(21.32386) translate(-39.1163 -23.3916)scale(.04688)"><path fill="#0000FF" d="M879.5 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.19 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89" display="inline"/><text x="857.49" y="564.94" fill="#0000ff" strokeWidth="1" direction="ltr" fontFamily="FreeSans" fontSize="64.03" fontWeight="bold" letterSpacing="-2.75" style={{ textAlign: "start" }} textAnchor="start" wordSpacing="0" writingMode="lr-tb"><tspan x="857.49" y="564.94" strokeWidth="1">A</tspan></text></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5.1299) scale(21.32386) translate(-39.1163 -23.3916)scale(.04688)"><path fill="#0000FF" d="M879.5 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.19 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89" display="inline"/><text x="857.49" y="564.94" fill="#0000ff" strokeWidth="1" direction="ltr" fontFamily="FreeSans" fontSize="64.03" fontWeight="bold" letterSpacing="-2.75" style={{ textAlign: "start" }} textAnchor="start" wordSpacing="0" writingMode="lr-tb"><tspan x="857.49" y="564.94" strokeWidth="1">A</tspan></text></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 5.1299) scale(21.32386) translate(-39.1163 -23.3916)scale(.04688)"><path fill="#0000FF" d="M879.5 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.19 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89" display="inline"/><text x="852.57" y="560.82" fill="#0000ff" strokeWidth="1" direction="ltr" fontFamily="FreeSans" fontSize="48.02" fontWeight="bold" letterSpacing="-2.75" style={{ textAlign: "start" }} textAnchor="start" wordSpacing="0" writingMode="lr-tb"><tspan x="852.57" y="560.82" strokeWidth="1" fontSize="48.02">Es</tspan></text></g></>
    ) }
  },
};
