// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4707: BabsIconDefinition = {
  id: "4707",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Andere", fr: "autres", it: "altri" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="#0000FF" d="M879.5 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.19 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89" display="inline" transform="translate(5 5.1299) scale(21.32386) translate(-39.1163 -23.3916)scale(.04688)"/></>
    ) }
  },
};
