// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4801: BabsIconDefinition = {
  id: "4801",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Trupp", fr: "Equipe", it: "Squadra" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(15.1465 5) scale(1.68963) translate(-24.3698 -12.2733)scale(.45356)"><circle cx="99.21" cy="38.99" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M99.21 50.92a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.85a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/><path fill="#0000FF" d="M99.21 144.5c-25.08 0-45.48-20.32-45.48-45.29s20.4-45.29 45.48-45.29 45.48 20.32 45.48 45.29-20.4 45.29-45.48 45.29m0-80.58c-19.56 0-35.48 15.83-35.48 35.29s15.92 35.29 35.48 35.29 35.48-15.83 35.48-35.29-15.91-35.29-35.48-35.29" display="inline"/></g></>
    ) }
  },
};
