// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4803: BabsIconDefinition = {
  id: "4803",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Zug", fr: "Section", it: "Sezione" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(15.5096 5) scale(1.69816) translate(-24.6873 -12.2234)scale(.45356)"><path fill="#0000FF" d="M99.21 143.8c-24.69 0-44.78-20-44.78-44.58s20.09-44.58 44.78-44.58 44.78 20 44.78 44.58-20.09 44.58-44.78 44.58m0-79.17c-19.18 0-34.78 15.51-34.78 34.58s15.6 34.58 34.78 34.58 34.78-15.51 34.78-34.58-15.6-34.58-34.78-34.58" display="inline"/><circle cx="129.07" cy="38.88" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M129.07 50.81a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.84a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/><circle cx="70.52" cy="38.88" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M70.52 50.81a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.84a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/><circle cx="99.21" cy="38.88" r="9.92" fill="#0000FF"/><path fill="#0000FF" d="M99.21 50.81a11.94 11.94 0 0 1 0-23.86 11.94 11.94 0 0 1 0 23.86m0-19.84a7.92 7.92 0 0 0 0 15.82 7.92 7.92 0 0 0 0-15.82"/></g></>
    ) }
  },
};
