// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4804: BabsIconDefinition = {
  id: "4804",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Kompanie", fr: "Companie", it: "Compania" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(19.7776 5) scale(14.32128 14.32129) translate(-39.1163 -21.3156)scale(.04688)"><path fill="#0000FF" d="M879.5 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.19 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89"/><path fill="#FFFFFF" d="M877.74 502.84 877.95 454.75"/><path fill="#0000FF" d="M853.8 474.3H901.88V483.3H853.8z" transform="rotate(-89.7575 877.845 478.7957)"/><path fill="#FFFFFF" d="M899.45 477.7 856.4 477.7"/><path fill="#0000FF" d="M856.4 473.2H899.4499999999999V482.2H856.4z"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(19.7776 5) scale(14.32128 14.32129) translate(-39.1163 -21.3156)scale(.04688)"><path fill="#0000FF" d="M879.5 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.19 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89"/><path fill="#FFFFFF" d="M877.74 502.84 877.95 454.75"/><path fill="#0000FF" d="M853.8 474.3H901.88V483.3H853.8z" transform="rotate(-89.7575 877.845 478.7957)"/><path fill="#FFFFFF" d="M899.45 477.7 856.4 477.7"/><path fill="#0000FF" d="M856.4 473.2H899.4499999999999V482.2H856.4z"/></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(19.7776 5) scale(14.32128 14.32129) translate(-39.1163 -21.3156)scale(.04688)"><path fill="#0000FF" d="M879.5 588.8c-24.82 0-45.02-20.14-45.02-44.89s20.2-44.89 45.02-44.89 45.02 20.14 45.02 44.89-20.19 44.89-45.02 44.89m0-79.77a35 35 0 0 0-35.02 34.89 35 35 0 0 0 35.02 34.89 35 35 0 0 0 35.02-34.89 35 35 0 0 0-35.02-34.89"/><path fill="#FFFFFF" d="M877.74 502.84 877.95 454.75"/><path fill="#0000FF" d="M853.8 474.3H901.88V483.3H853.8z" transform="rotate(-89.7575 877.845 478.7957)"/><path fill="#FFFFFF" d="M899.45 477.7 856.4 477.7"/><path fill="#0000FF" d="M856.4 473.2H899.4499999999999V482.2H856.4z"/></g></>
    ) }
  },
};
