// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4806: BabsIconDefinition = {
  id: "4806",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Einsatzleiter", fr: "DI", it: "Capointervento" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(27.9122 5) scale(10.34483) translate(-37.4602 -20.1052)scale(.04688)"><path fill="#0000FF" d="M844.7 614.51a45.57 45.57 0 0 1-45.55-45.47 45.56 45.56 0 0 1 91.1 0 45.56 45.56 0 0 1-45.55 45.47m0-80.93a35.55 35.55 0 0 0-35.55 35.47 35.55 35.55 0 0 0 71.1 0 35.55 35.55 0 0 0-35.55-35.47"/><path fill="#FFFFFF" d="M843.92 527.38 844.12 428.99"/><path fill="#0000FF" d="M794.83 473.68H893.22V482.68H794.83z" transform="rotate(-89.8819 844.0214 478.1843)"/><path fill="#FFFFFF" d="M841.02 433.41 875.7 433.41"/><path fill="#0000FF" d="M841.02 428.91H875.6999999999999V437.91H841.02z"/><path fill="#FFFFFF" d="M841.02 456.56 875.7 456.56"/><path fill="#0000FF" d="M841.02 452.06H875.6999999999999V461.06H841.02z"/><path fill="#FFFFFF" d="M841.02 480.17 875.7 480.17"/><path fill="#0000FF" d="M841.02 475.67H875.6999999999999V484.67H841.02z"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(27.9122 5) scale(10.34483) translate(-37.4602 -20.1052)scale(.04688)"><path fill="#0000FF" d="M844.7 614.51a45.57 45.57 0 0 1-45.55-45.47 45.56 45.56 0 0 1 91.1 0 45.56 45.56 0 0 1-45.55 45.47m0-80.93a35.55 35.55 0 0 0-35.55 35.47 35.55 35.55 0 0 0 71.1 0 35.55 35.55 0 0 0-35.55-35.47"/><path fill="#FFFFFF" d="M843.92 527.38 844.12 428.99"/><path fill="#0000FF" d="M794.83 473.68H893.22V482.68H794.83z" transform="rotate(-89.8819 844.0214 478.1843)"/><path fill="#FFFFFF" d="M841.02 433.41 875.7 433.41"/><path fill="#0000FF" d="M841.02 428.91H875.6999999999999V437.91H841.02z"/><path fill="#FFFFFF" d="M841.02 456.56 875.7 456.56"/><path fill="#0000FF" d="M841.02 452.06H875.6999999999999V461.06H841.02z"/><path fill="#FFFFFF" d="M841.02 480.17 875.7 480.17"/><path fill="#0000FF" d="M841.02 475.67H875.6999999999999V484.67H841.02z"/></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(27.9122 5) scale(10.34483) translate(-37.4602 -20.1052)scale(.04688)"><path fill="#0000FF" d="M844.7 614.51a45.57 45.57 0 0 1-45.55-45.47 45.56 45.56 0 0 1 91.1 0 45.56 45.56 0 0 1-45.55 45.47m0-80.93a35.55 35.55 0 0 0-35.55 35.47 35.55 35.55 0 0 0 71.1 0 35.55 35.55 0 0 0-35.55-35.47"/><path fill="#FFFFFF" d="M843.92 527.38 844.12 428.99"/><path fill="#0000FF" d="M794.83 473.68H893.22V482.68H794.83z" transform="rotate(-89.8819 844.0214 478.1843)"/><path fill="#FFFFFF" d="M841.02 433.41 875.7 433.41"/><path fill="#0000FF" d="M841.02 428.91H875.6999999999999V437.91H841.02z"/><path fill="#FFFFFF" d="M841.02 456.56 875.7 456.56"/><path fill="#0000FF" d="M841.02 452.06H875.6999999999999V461.06H841.02z"/><path fill="#FFFFFF" d="M841.02 480.17 875.7 480.17"/><path fill="#0000FF" d="M841.02 475.67H875.6999999999999V484.67H841.02z"/></g></>
    ) }
  },
};
