// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4807: BabsIconDefinition = {
  id: "4807",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Gruppenführer", fr: "Chef de groupe", it: "Cappogruppo" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(27.8609 5) scale(10.36885) translate(-36.609 -20.2444)scale(.04688)"><path fill="#0000FF" d="M826.54 617.05c-25.11 0-45.55-20.37-45.55-45.41a45 45 0 0 1 13.35-32.12 45.3 45.3 0 0 1 32.2-13.29c25.11 0 45.55 20.37 45.55 45.41s-20.44 45.41-45.55 45.41m0-80.83c-9.5 0-18.43 3.69-25.14 10.38a35.1 35.1 0 0 0-10.41 25.04 35.5 35.5 0 0 0 35.55 35.41 35.53 35.53 0 0 0 35.55-35.41 35.53 35.53 0 0 0-35.55-35.42"/><path fill="#FFFFFF" d="M824.76 530.03 824.96 431.94"/><path fill="#0000FF" d="M775.81 476.48H873.9V485.48H775.81z" transform="rotate(-89.8819 824.8608 480.9817)"/><path fill="#FFFFFF" d="M820.45 436.38 855.13 436.38"/><path fill="#0000FF" d="M820.45 431.88H855.13V440.88H820.45z"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(27.8609 5) scale(10.36885) translate(-36.609 -20.2444)scale(.04688)"><path fill="#0000FF" d="M826.54 617.05c-25.11 0-45.55-20.37-45.55-45.41a45 45 0 0 1 13.35-32.12 45.3 45.3 0 0 1 32.2-13.29c25.11 0 45.55 20.37 45.55 45.41s-20.44 45.41-45.55 45.41m0-80.83c-9.5 0-18.43 3.69-25.14 10.38a35.1 35.1 0 0 0-10.41 25.04 35.5 35.5 0 0 0 35.55 35.41 35.53 35.53 0 0 0 35.55-35.41 35.53 35.53 0 0 0-35.55-35.42"/><path fill="#FFFFFF" d="M824.76 530.03 824.96 431.94"/><path fill="#0000FF" d="M775.81 476.48H873.9V485.48H775.81z" transform="rotate(-89.8819 824.8608 480.9817)"/><path fill="#FFFFFF" d="M820.45 436.38 855.13 436.38"/><path fill="#0000FF" d="M820.45 431.88H855.13V440.88H820.45z"/></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(27.8609 5) scale(10.36885) translate(-36.609 -20.2444)scale(.04688)"><path fill="#0000FF" d="M826.54 617.05c-25.11 0-45.55-20.37-45.55-45.41a45 45 0 0 1 13.35-32.12 45.3 45.3 0 0 1 32.2-13.29c25.11 0 45.55 20.37 45.55 45.41s-20.44 45.41-45.55 45.41m0-80.83c-9.5 0-18.43 3.69-25.14 10.38a35.1 35.1 0 0 0-10.41 25.04 35.5 35.5 0 0 0 35.55 35.41 35.53 35.53 0 0 0 35.55-35.41 35.53 35.53 0 0 0-35.55-35.42"/><path fill="#FFFFFF" d="M824.76 530.03 824.96 431.94"/><path fill="#0000FF" d="M775.81 476.48H873.9V485.48H775.81z" transform="rotate(-89.8819 824.8608 480.9817)"/><path fill="#FFFFFF" d="M820.45 436.38 855.13 436.38"/><path fill="#0000FF" d="M820.45 431.88H855.13V440.88H820.45z"/></g></>
    ) }
  },
};
