// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs4808: BabsIconDefinition = {
  id: "4808",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Offizier-Zugführer", fr: "Officier-Chef de section", it: "Uffiziale-Caposezione" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(27.9865 5) scale(10.37838) translate(-52.2797 -21.12)scale(.04688)"><path fill="#0000FF" d="M1160.55 635.56a45.35 45.35 0 0 1 0-90.68 45.35 45.35 0 0 1 0 90.68m0-80.68a35.34 35.34 0 0 0-35.25 35.34 35.33 35.33 0 0 0 35.25 35.34 35.33 35.33 0 0 0 35.25-35.34 35.34 35.34 0 0 0-35.25-35.34"/><path fill="#FFFFFF" d="M1158.84 548.69 1159.05 450.61"/><path fill="#0000FF" d="M1109.91 495.15H1207.99V504.15H1109.91z" transform="rotate(-89.8819 1158.9458 499.6487)"/><path fill="#FFFFFF" d="M1154.55 455.05 1189.03 455.05"/><path fill="#0000FF" d="M1154.55 450.56H1189.03V459.56H1154.55z"/><path fill="#FFFFFF" d="M1155.39 478.82 1189.87 478.82"/><path fill="#0000FF" d="M1155.39 474.32H1189.8700000000001V483.32H1155.39z"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(27.9865 5) scale(10.37838) translate(-52.2797 -21.12)scale(.04688)"><path fill="#0000FF" d="M1160.55 635.56a45.35 45.35 0 0 1 0-90.68 45.35 45.35 0 0 1 0 90.68m0-80.68a35.34 35.34 0 0 0-35.25 35.34 35.33 35.33 0 0 0 35.25 35.34 35.33 35.33 0 0 0 35.25-35.34 35.34 35.34 0 0 0-35.25-35.34"/><path fill="#FFFFFF" d="M1158.84 548.69 1159.05 450.61"/><path fill="#0000FF" d="M1109.91 495.15H1207.99V504.15H1109.91z" transform="rotate(-89.8819 1158.9458 499.6487)"/><path fill="#FFFFFF" d="M1154.55 455.05 1189.03 455.05"/><path fill="#0000FF" d="M1154.55 450.56H1189.03V459.56H1154.55z"/><path fill="#FFFFFF" d="M1155.39 478.82 1189.87 478.82"/><path fill="#0000FF" d="M1155.39 474.32H1189.8700000000001V483.32H1155.39z"/></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(27.9865 5) scale(10.37838) translate(-52.2797 -21.12)scale(.04688)"><path fill="#0000FF" d="M1160.55 635.56a45.35 45.35 0 0 1 0-90.68 45.35 45.35 0 0 1 0 90.68m0-80.68a35.34 35.34 0 0 0-35.25 35.34 35.33 35.33 0 0 0 35.25 35.34 35.33 35.33 0 0 0 35.25-35.34 35.34 35.34 0 0 0-35.25-35.34"/><path fill="#FFFFFF" d="M1158.84 548.69 1159.05 450.61"/><path fill="#0000FF" d="M1109.91 495.15H1207.99V504.15H1109.91z" transform="rotate(-89.8819 1158.9458 499.6487)"/><path fill="#FFFFFF" d="M1154.55 455.05 1189.03 455.05"/><path fill="#0000FF" d="M1154.55 450.56H1189.03V459.56H1154.55z"/><path fill="#FFFFFF" d="M1155.39 478.82 1189.87 478.82"/><path fill="#0000FF" d="M1155.39 474.32H1189.8700000000001V483.32H1155.39z"/></g></>
    ) }
  },
};
