// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5105: BabsIconDefinition = {
  id: "5105",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Patientensammelstelle", fr: "Poste-collecteur-de-patients", it: "Posto-collettore-dei-pazienti" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(20.5908 5) scale(.72347)"><path fill="#0000FF" d="M81.3 124.4H0V0h81.3zm-75-6.3H75V6.3H6.3Z"/><path fill="#0000FF" d="M37.9 3.6H42.1V121.8H37.9z"/><path fill="#0000FF" d="M4.9 60.3H77.30000000000001V64.5H4.9z"/></g></>
    ) }
  },
};
