// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5106: BabsIconDefinition = {
  id: "5106",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Sanitaetshilfsstelle", fr: "Poste-medical-avance", it: "Posto-di-soccorso-sanitario" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(20.691 5) scale(.71485)"><path fill="#0000FF" d="M82 125.9H0V0h82zm-75-7h68V7H7Z"/><path fill="#0000FF" d="M6.1 67H75.3V71.2H6.1z"/><path fill="#0000FF" d="M6.6 51.7H75.39999999999999V55.900000000000006H6.6z"/><path fill="#0000FF" d="M38.6 3.5H42.800000000000004V122.4H38.6z"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(20.691 5) scale(.71485)"><path fill="#0000FF" d="M82 125.9H0V0h82zm-75-7h68V7H7Z"/><path fill="#0000FF" d="M6.1 67H75.3V71.2H6.1z"/><path fill="#0000FF" d="M6.6 51.7H75.39999999999999V55.900000000000006H6.6z"/><path fill="#0000FF" d="M38.6 3.5H42.800000000000004V122.4H38.6z"/></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(20.691 5) scale(.71485)"><path fill="#0000FF" d="M82 125.9H0V0h82zm-75-7h68V7H7Z"/><path fill="#0000FF" d="M6.1 67H75.3V71.2H6.1z"/><path fill="#0000FF" d="M6.6 51.7H75.39999999999999V55.900000000000006H6.6z"/><path fill="#0000FF" d="M38.6 3.5H42.800000000000004V122.4H38.6z"/></g></>
    ) }
  },
};
