// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5107: BabsIconDefinition = {
  id: "5107",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Fahrzeugplatz", fr: "Place pour véhicules", it: "Posteggio veicoli" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 19.6484) scale(.75352)"><path fill="blue" strokeWidth="0" d="M40.94 53.44V27.87h17.52v4.33H46.1v6.05h10.67v4.32H46.1v10.87zM60.81 53.44v-3.82l6.94-7.97a59 59 0 0 1 2.53-2.77q-.85.06-2.25.07l-6.54.04v-4.06H76.8v3.47l-7.08 8.16-2.49 2.7q2.04-.12 2.53-.12h7.58v4.31H60.81Z"/><path fill="blue" strokeWidth="0" d="M119.44 80.56H0V0h119.44ZM5.55 75.01h108.33V5.56H5.56V75Z"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 19.6516) scale(.7742)"><path fill="#FFFFFF" d="M348.18 433.9H234.53v-75.68h113.65Zm-112.97-.69h112.28V358.9H235.21Z" transform="translate(-233.22 -356.92)"/><g transform="translate(-233.22 -356.92)"><path fill="#0000FF" d="m267.88 408.92-8.89-24.88h5.45l6.3 18.42 6.09-18.42h5.33l-8.91 24.88zM289.43 384.04v9.15a7 7 0 0 1 5.51-2.7q1.65 0 2.97.61a4.9 4.9 0 0 1 2.91 3.66q.25 1.15.25 3.58v10.57h-4.77v-9.52q0-2.83-.27-3.6-.27-.76-.96-1.21a3 3 0 0 0-1.72-.45q-1.19 0-2.12.58-.93.57-1.37 1.74-.43 1.16-.43 3.44v9.03h-4.77v-24.88zM321.62 396.23l-4.7.85a3.4 3.4 0 0 0-1.08-2.12 3.2 3.2 0 0 0-2.18-.71q-1.79 0-2.84 1.23-1.06 1.23-1.06 4.12 0 3.21 1.08 4.53a3.5 3.5 0 0 0 2.89 1.32 3.2 3.2 0 0 0 2.22-.77q.87-.77 1.22-2.66l4.68.8q-.73 3.22-2.8 4.87t-5.55 1.65q-3.96 0-6.3-2.5-2.35-2.5-2.35-6.91 0-4.47 2.36-6.95t6.38-2.49q3.29 0 5.23 1.42a8 8 0 0 1 2.8 4.32"/><path fill="#0000FF" d="M349.47 435.32H233.22v-78.4h116.25Zm-110.84-5.41h105.44v-67.59H238.63Z"/></g></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 19.6517) scale(.75994)"><path fill="#FFFFFF" d="M348.17 433.99H234.52V358.3h113.64zm-112.96-.69h112.27v-74.31H235.21Z" transform="translate(-232.13 -356.21)"/><g transform="translate(-232.13 -356.21)"><path fill="#0000FF" d="m272.95 409.19-9.06-25.35h5.55l6.41 18.76 6.21-18.76h5.43l-9.08 25.35zM300.69 403.35l4.84.81a8 8 0 0 1-2.95 4.06 8.6 8.6 0 0 1-5.04 1.39q-4.79 0-7.09-3.13-1.81-2.5-1.81-6.33 0-4.57 2.39-7.15a7.9 7.9 0 0 1 6.03-2.59q4.1 0 6.46 2.71t2.26 8.29h-12.17a5 5 0 0 0 1.18 3.36q1.12 1.2 2.8 1.2a3 3 0 0 0 1.92-.62q.78-.62 1.18-2m.28-4.91q-.06-2.12-1.09-3.21a3.3 3.3 0 0 0-2.52-1.1q-1.6 0-2.63 1.16a4.5 4.5 0 0 0-1.02 3.15zM309.75 388.34v-4.5h4.86v4.5zm0 20.85v-18.36h4.86v18.36z"/><path fill="#0000FF" d="M350.56 436.08H232.13v-79.87h118.43Zm-112.92-5.51h107.42v-68.86H237.64Z"/></g></g></>
    ) }
  },
};
