// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5111: BabsIconDefinition = {
  id: "5111",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Totensammelstelle", fr: "Poste-collecteur-de-morts", it: "Posto-colletore-dei-morti" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(21.0008 5) scale(.70644)"><path fill="#FFFFFF" d="M3.5 3.5 78.5 3.5 78.5 123.9 3.5 123.9z"/><path fill="#0000FF" d="M82.1 127.4H0V0h82.1zm-75-7.1H75V7.1H7.1Z"/><path fill="#0000FF" d="M38.8 20.8H44.5V108.8H38.8z"/><path fill="#0000FF" d="M21.4 40.5H60.699999999999996V46.2H21.4z"/></g></>
    ) }
  },
};
