// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5119: BabsIconDefinition = {
  id: "5119",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Streugutsammelstelle", fr: "Poste collecteur des objets trouvés", it: "Posto colletore degli aggretti trovati" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="#0303ff" stroke="none" d="M1 0v807h534V0zm497 38v281H39V38zm0 306v59H39v-59zm0 84v342H39V428zM169 543h-45v162l1.03 12.4L143 719h263V543h-30c-3.71 0-9.43 1.03-12.72-1.03-4.87-3.05-7.33-14.92-10.3-19.97-7.3-12.5-17.04-23.41-28.98-31.65-41.99-28.97-98.28-21.65-133.17 14.74-9.58 10-19.43 23.95-21.83 37.91m166 0H196c17.32-60 121.69-59.98 139 0m46 25v125H149V568Z" transform="translate(20.223 5) scale(1.00124) translate(-.1114) scale(.11139)"/></>
    ) }
  },
};
