// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5120: BabsIconDefinition = {
  id: "5120",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Trinkwasserabgabestelle", fr: "Poste de distribution d'eau potable", it: "Posto di distribuzione acqua potabile" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="#0000ff" stroke="none" d="M1 1v745h485V1zm448 38v669H38V39zM221 310v57H85v29h150c26.6 0 56.4-3.77 82 4.67 20.36 6.7 38.68 20.49 47.69 40.33 5.56 12.26 1.79 39.92 22.31 36.79 11.26-1.73 12.83-13.5 11.71-22.79-2.31-19.37-10.18-37.79-23.75-52-34.64-36.3-77.43-36-123.96-36v-57c9.52 0 24.5 2.82 33-2.09 9.24-5.34 9.6-20.27-.02-25.47-7.72-4.17-18.52-2.44-26.98-2.44h-46c-7.41 0-16.06-1.19-23 1.97-10.37 4.72-10.74 20.3-1 25.94 8.7 5.03 24.24 2.09 34 2.09" transform="translate(20.7047 5) scale(1.00134) translate(-.1206 -.1206) scale(.12064)"/></>
    ) }
  },
};
