// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5125: BabsIconDefinition = {
  id: "5125",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Absperrung Verkehrswege", fr: "Fermeture de la route", it: "Sbarramento delle vie di comunicazione" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(39.0624 5) scale(.98855) translate(-34.5218 .1403)scale(.08214)"><path fill="#0000ff" stroke="none" d="M689 39 469 303l-48-39L642-1Z"/><path fill="none" stroke="#0000ff" strokeWidth="1" d="M689 39 469 303l-48-39L642-1Z"/><path fill="#0000ff" stroke="none" d="m469 802 220 264-47 40-221-264z"/><path fill="none" stroke="#0000ff" strokeWidth="1" d="m469 802 220 264-47 40-221-264z"/><path fill="#0000ff" stroke="none" d="M483 264v577h-62V264Z"/><path fill="none" stroke="#0000ff" strokeWidth="1" d="M483 264v577h-62V264Z"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(39.0624 5)scale(.98855) translate(-34.5218 .1403)scale(.08214)"><path fill="#0000ff" stroke="none" d="M689 39 469 303l-48-39L642-1Z"/><path fill="none" stroke="#0000ff" strokeWidth="1" d="M689 39 469 303l-48-39L642-1Z"/><path fill="#0000ff" stroke="none" d="m469 802 220 264-47 40-221-264z"/><path fill="none" stroke="#0000ff" strokeWidth="1" d="m469 802 220 264-47 40-221-264z"/><path fill="#0000ff" stroke="none" d="M483 264v577h-62V264Z"/><path fill="none" stroke="#0000ff" strokeWidth="1" d="M483 264v577h-62V264Z"/></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(39.0624 5)scale(.98855) translate(-34.5218 .1403)scale(.08214)"><path fill="#0000ff" stroke="none" d="M689 39 469 303l-48-39L642-1Z"/><path fill="none" stroke="#0000ff" strokeWidth="1" d="M689 39 469 303l-48-39L642-1Z"/><path fill="#0000ff" stroke="none" d="m469 802 220 264-47 40-221-264z"/><path fill="none" stroke="#0000ff" strokeWidth="1" d="m469 802 220 264-47 40-221-264z"/><path fill="#0000ff" stroke="none" d="M483 264v577h-62V264Z"/><path fill="none" stroke="#0000ff" strokeWidth="1" d="M483 264v577h-62V264Z"/></g></>
    ) }
  },
};
