// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5132a: BabsIconDefinition = {
  id: "5132a",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Beobachtung", fr: "Observation", it: "Osservazione" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="#0000FF" d="M82 69.9H0L41 0Zm-75-4h68l-34-58Z" transform="translate(5 11.6402) scale(1.09756)"/></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="#0000FF" d="M82 69.9H0L41 0Zm-75-4h68l-34-58Z" transform="translate(5 11.6402) scale(1.09756)"/></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="#0000FF" d="M82 69.9H0L41 0Zm-75-4h68l-34-58Z" transform="translate(5 11.6402) scale(1.09756)"/></>
    ) }
  },
};
