// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5135: BabsIconDefinition = {
  id: "5135",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "KGS-Notdepot", fr: "Depot-d-urgence-PBC", it: "Deposito PBC di fortuna" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g display="inline" transform="translate(22.1461 5) scale(.6886)"><path fill="#0000FF" d="M80.9 43.2 80.9 130.7 75 130.7 75 45.6 38.9 8.7 5.9 45.5 5.9 130.7 0 130.7 0 43.2 38.7 0z" display="inline"/><g transform="matrix(1.5128 0 0 1.51189 -92.8441 -37.779)"><path fill="#ffffff" strokeWidth=".96" d="M71.02 54.84H104.50999999999999V88.35H71.02z" display="inline" transform="translate(59.9135 23.3244)scale(.6886) translate(-87.0078 -33.8722)scale(1.45222)"/><g transform="translate(59.9135 23.3244)scale(.6886)"><path fill="#0000ff" fillRule="evenodd" d="M64.7 46 40.5 70.2 16.4 46" clipRule="evenodd" display="inline"/><path fill="#0000ff" d="M23.4 77.4H57.6V111.60000000000001H23.4z" transform="rotate(-45 40.539 94.5267)"/></g></g></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g display="inline" transform="translate(22.1461 5) scale(.6886)"><path fill="#0000FF" d="M0 43.2 38.7 0 80.9 43.2 80.9 130.7 75 130.7 75 45.6 38.9 8.7 5.9 45.5 5.9 130.7 0 130.7z" display="inline"/><g transform="matrix(1.5128 0 0 1.51189 -92.8441 -37.779)"><path fill="#ffffff" strokeWidth=".96" d="M71.02 54.84H104.50999999999999V88.35H71.02z" display="inline" transform="translate(59.9135 23.3244)scale(.6886) translate(-87.0078 -33.8722)scale(1.45222)"/><g transform="translate(59.9135 23.3244)scale(.6886)"><path fill="#0000ff" fillRule="evenodd" d="M64.7 46 40.5 70.2 16.4 46" clipRule="evenodd" display="inline"/><path fill="#0000ff" d="M23.4 77.4H57.6V111.60000000000001H23.4z" transform="rotate(-45 40.539 94.5267)"/></g></g></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g display="inline" transform="translate(22.1461 5) scale(.6886)"><path fill="#0000FF" d="M0 43.2 38.7 0 80.9 43.2 80.9 130.7 75 130.7 75 45.6 38.9 8.7 5.9 45.5 5.9 130.7 0 130.7z" display="inline"/><g transform="matrix(1.5128 0 0 1.51189 -92.8441 -37.779)"><path fill="#ffffff" strokeWidth=".96" d="M71.02 54.84H104.50999999999999V88.35H71.02z" display="inline" transform="translate(59.9135 23.3244)scale(.6886) translate(-87.0078 -33.8722)scale(1.45222)"/><g transform="translate(59.9135 23.3244)scale(.6886)"><path fill="#0000ff" fillRule="evenodd" d="M64.7 46 40.5 70.2 16.4 46" clipRule="evenodd" display="inline"/><path fill="#0000ff" d="M23.4 77.4H57.6V111.60000000000001H23.4z" transform="rotate(-45 40.539 94.5267)"/></g></g></g></>
    ) }
  },
};
