// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs5135: BabsIconDefinition = {
  id: "5135",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "KGS-Notdepot", fr: "Depot-d-urgence-PBC", it: "Deposito PBC di fortuna" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(22.1461 5) scale(.6886)"><path fill="#0000FF" d="M6.6 124.9H72.89999999999999V127.7H6.6z"/><path fill="#FFFFFF" d="M3.6 121.9H75.89999999999999V130.70000000000002H3.6z"/><path fill="#FFFFFF" d="M3 127.8V44.4l35.9-40 39.1 40v83.4"/><path fill="#0000FF" d="M80.9 43.2 80.9 130.7 75 130.7 75 45.6 38.9 8.7 5.9 45.5 5.9 130.7 0 130.7 0 43.2 38.7 0z"/><path fill="#0000FF" fillRule="evenodd" d="M64.7 46 40.5 70.2 16.4 46" clipRule="evenodd"/><path d="M64.8 94.6H16.1V46h48.7Zm-48.5-.2h48.3V46.1H16.3Z"/><path fill="#0000FF" d="M23.4 77.4H57.6V111.60000000000001H23.4z" transform="rotate(-45 40.539 94.5267)"/></g></>
    ) }
  },
};
