// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs6102a: BabsIconDefinition = {
  id: "6102a",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Beabsichtigter Einsatz", fr: "Engagement-prevu", it: "Intervento pianificato" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 43.0882) scale(.17215)"><path fill="#0000FF" d="M0 31.3H31.6V49H0z"/><path fill="#0000FF" d="m363.3 49-66.4-.1V31.3h66.4zm-82.9 0-66.4-.1V31.3h66.4zm-82.9 0-66.4-.1V31.3h66.4zm-82.9 0-66.4-.1.1-17.6h66.4V49Z"/><path fill="#0000FF" d="M379.8 31.3H411.5V49H379.8z"/><path fill="#0000FF" d="M520 40.1 458.8 77.6 458.8 2.6z"/><path fill="#0000FF" d="M457.3 80.3V0l65.5 40.1zm3-75V75l56.9-34.9z"/><path fill="#0000FF" d="M520 40.1 458.8 77.6 458.8 2.6z"/><path fill="#0000FF" d="M457.3 80.3V0l65.5 40.1zm3-75V75l56.9-34.9z"/><path fill="#0000FF" d="M457.8 40.1 396.6 77.6 396.6 2.6z"/><path fill="#0000FF" d="M395.1 80.3V0l65.5 40.1zm3-75V75L455 40.1Z"/><path fill="#0000FF" d="M457.8 40.1 396.6 77.6 396.6 2.6z"/><path fill="#0000FF" d="M395.1 80.3V0l65.5 40.1zm3-75V75L455 40.1Z"/></g></>
    ) }
  },
};
