// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs7104: BabsIconDefinition = {
  id: "7104",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Transportfahrzeug", fr: "Vehicule-de-transport-bus", it: "Veicoli per il trasporto (Bus)" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 17.8653) scale(1.14358)"><circle cx="39.5" cy="46.2" r="8.4" fill="#FFFFFF"/><path fill="#0000FF" d="M39.5 56.2c-5.6 0-10.1-4.5-10.1-10.1S33.9 36 39.5 36s10.1 4.5 10.1 10.1S45 56.2 39.5 56.2m0-16.7a6.7 6.7 0 1 0 0 13.4 6.7 6.7 0 0 0 0-13.4"/><circle cx="16.6" cy="46.2" r="8.4" fill="#FFFFFF"/><path fill="#0000FF" d="M16.6 56.2c-5.6 0-10.1-4.5-10.1-10.1S11 36 16.6 36s10.1 4.5 10.1 10.1-4.5 10.1-10.1 10.1m0-16.7a6.7 6.7 0 1 0 0 13.4 6.7 6.7 0 0 0 0-13.4"/><circle cx="62.3" cy="46.2" r="8.4" fill="#FFFFFF"/><path fill="#0000FF" d="M62.3 56.2c-5.6 0-10.1-4.5-10.1-10.1S56.7 36 62.3 36s10.1 4.5 10.1 10.1-4.5 10.1-10.1 10.1m0-16.7a6.7 6.7 0 1 0 0 13.4 6.7 6.7 0 0 0 0-13.4"/><path fill="#FFFFFF" d="M76.8 2.4 58.3 7.5 46.1 9.8 39.3 10.2 31.8 9.6 20.5 7.4 1.9 2.4 1.9 18.5 1.9 34.6 39.3 34.6 76.8 34.6 76.8 18.5z"/><path fill="#0000FF" d="M78.7 36.5H0V0l20.9 5.5 11.2 2.2 7.3.5 6.5-.4 12-2.2L78.7 0Zm-75-3.7H75v-28L58.6 9.3l-12.4 2.3-6.9.4-7.9-.6L20 9.1 3.7 4.8Z"/></g></>
    ) }
  },
};
