// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs7105: BabsIconDefinition = {
  id: "7105",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Lastwagen", fr: "Camion-poids-lourd", it: "Autocarro" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 17.8571) scale(1.14796)"><circle cx="46.1" cy="46" r="8.4" fill="#FFFFFF"/><path fill="#0000FF" d="M46.1 56a10.05 10.05 0 1 1 0-20.1 10.05 10.05 0 1 1 0 20.1m0-16.7a6.7 6.7 0 1 0 0 13.4 6.7 6.7 0 0 0 0-13.4"/><circle cx="13.1" cy="46" r="8.4" fill="#FFFFFF"/><path fill="#0000FF" d="M13.1 56a10.05 10.05 0 1 1 0-20.1 10.05 10.05 0 1 1 0 20.1m0-16.7a6.7 6.7 0 1 0 0 13.4 6.7 6.7 0 0 0 0-13.4"/><circle cx="67.2" cy="46" r="8.4" fill="#FFFFFF"/><path fill="#0000FF" d="M67.2 56c-5.6 0-10.1-4.5-10.1-10.1s4.5-10.1 10.1-10.1 10.1 4.5 10.1 10.1S72.8 56 67.2 56m0-16.7a6.7 6.7 0 1 0 0 13.4 6.7 6.7 0 0 0 0-13.4"/><path fill="#FFFFFF" d="M76.7 2.2 58.2 7.3 46 9.6 39.2 10 31.6 9.4 20.3 7.2 1.7 2.2 1.7 18.3 1.7 34.4 39.2 34.4 76.7 34.4 76.7 18.3z"/><path fill="#0000FF" d="M78.4 36.1H0V0l20.7 5.5 11.2 2.2 7.3.5 6.6-.4 12-2.2L78.4 0Zm-75-3.3H75V4.4L58.5 8.9l-12.4 2.3-6.9.4-7.9-.6-11.4-2.2L3.4 4.4Z"/></g></>
    ) }
  },
};
