// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs7113: BabsIconDefinition = {
  id: "7113",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Helikopter", fr: "Helicoptere", it: "Elicottero" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 37.1675) scale(1.1509)"><path fill="#0000FF" d="M37.5 2.7H40.7V22.3H37.5z"/><path fill="#FFFFFF" d="M38.6 8.4 1.6 14.4 1.6 1.9z"/><path fill="#0000FF" d="M0 16.2V0l48.1 8.5ZM3.2 3.8v8.7L29 8.4Z"/><path fill="#FFFFFF" d="M39.6 8.6 76.6 2.7 76.6 15.1z"/><path fill="#0000FF" d="M78.2 17 30 8.5 78.1.8V17ZM49.1 8.7 75 13.3V4.5Z"/></g></>
    ) }
  },
};
