// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs7115: BabsIconDefinition = {
  id: "7115",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Wasserwerfer", fr: "Canon-a-eau", it: "Lanciaacqua" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 25.94) scale(.6)"><path fill="#0000FF" d="M150 80.2H0V0h150ZM5.2 75h139.5V5.2H5.2Z" display="inline"/><path fill="#0000FF" d="M98.1 75V5l45.8 35zm5.1-59.6v49.2L135.4 40Z" display="inline"/><path fill="#0000FF" d="m24 48.5-4.8-20.1h4.2l3 13.8L30 28.4h4.8l3.5 14 3.1-14h4.1l-4.9 20.1h-4.3l-4-15-4 15z" display="inline" enableBackground="new"/><path fill="#0000FF" d="M64.1 34.6H96.8V44H64.1z" display="inline"/><path fill="#0000FF" d="M111.2 39.3 92 53.7 92 25z" display="inline"/><path fill="#0000FF" d="M49.8 39.4c0-3.5 2.8-6.3 6.4-6.3a6.3 6.3 0 1 1 0 12.6c-3.5 0-6.4-2.8-6.4-6.3" display="inline"/></g></>
    ) }
  },
};
