// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs7116: BabsIconDefinition = {
  id: "7116",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Hubrettungsfahrzeug", fr: "Elevateur-a-nacelle", it: "Elevatore-a-navicella" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 25.94) scale(.6)"><path fill="#0000FF" d="M150 80.2H0V0h150ZM5.2 75h139.5V5.2H5.2Z"/><path fill="#0000FF" d="M100.2 2.6H105.3V77.6H100.2z"/><path fill="#0000FF" d="M95.8 56.3H154.2V61.4H95.8z" transform="rotate(-40.007 124.9637 58.8451)"/><path fill="#0000FF" d="M122.6-7.7H127.69999999999999V50.4H122.6z" transform="rotate(-49.998 125.1911 21.361)"/><path fill="#0000FF" d="M3.6 79.3 1 74.9l52.3-30.2c-4.2-1.1-8.4-2.1-12.5-3.2-6.3-1.6-12.9-3.2-19.3-4.9l1.3-5c6.4 1.7 12.9 3.3 19.2 4.9 6.1 1.5 12.4 3.1 18.6 4.8l6 1.6z"/></g></>
    ) }
  },
};
