// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs7117: BabsIconDefinition = {
  id: "7117",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Autodrehleiter", fr: "Echelle pivotante aérienne", it: "Scala-motorizzata" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><path fill="#0000FF" d="M123.12.21v74.8H.22c-.4-24.9-.1-49.8-.2-74.7 41-.5 82.1-.3 123.1-.1m-119 70.8h78.9v-16H4.12Zm0-51.7h78.9V4.11H4.12Zm83.2-9.3v54.7c9.8-9.3 19.3-18.3 29-27.4-9.7-9.2-19.3-18.2-29-27.3m31.7 61.1v-30.7c-10.8 10.2-21.4 20.3-32.4 30.6h32.4zm0-36.8V4.11h-31.8c10.8 10.2 21.2 20.1 31.8 30.2m-99.3 16.4h12.9v-27.2h-12.9zm30.8.1v-27.3h-13v27.2h13zm17.1 0v-27.3h-12.3v27.2h12.3zm-63.5-27.3v27.3h11.3v-27.3zm67.7 0v27.2h11.2v-27.2z" transform="translate(5 22.5816) scale(.73102)"/></>
    ) }
  },
};
