// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "../types.js";

export const babs7118: BabsIconDefinition = {
  id: "7118",
  viewBox: "0 0 100 100",
  canonicalLang: "de",
  labels: { de: "Tanklöschfahrzeug", fr: "Fourgon-Tonne-pompe", it: "Autobotte" },
  recolorable: false,
  displaySize: 32,
  graphics: {
    "de": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 26.7358) scale(1.16234)"><path fill="#fff" strokeWidth="0" d="M76.22 1.22 76.22 38.81 1.22 38.81 1.22 1.22z"/><path fill="blue" strokeWidth="0" d="M77.43 40.03H0V0h77.43Zm-75-2.43H75V2.43H2.43v35.16z"/><path fill="#fff" strokeWidth="0" d="M73.09 20.11 52.86 35.57 52.86 4.65z"/><path fill="blue" strokeWidth="0" d="M51.64 38.04V2.19L75.1 20.11zm2.43-30.93v26l17.02-13zM17.15 24.97V16.3h-3.09v-1.76h8.28v1.76h-3.09v8.67zM23.76 24.97V14.63h2.1v8.59h5.23v1.76h-7.34zM32.61 24.97V14.54h7.15v1.76h-5.04v2.47h4.35v1.76h-4.35v4.43z"/></g></>
    ) },
    "fr": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 26.7382) scale(.58264) translate(-221.3 -381.02)"><path fill="#FFFFFF" d="M223.73 383.44H373.35V458.44H223.73z"/><path fill="#0000FF" d="M375.77 460.87H221.3v-79.85h154.47Zm-149.61-4.85h144.76v-70.14H226.16Z"/><path fill="#FFFFFF" d="M367.12 421.14 326.74 451.98 326.74 390.29z"/><path fill="#0000FF" d="M324.32 456.89v-71.52l46.8 35.76zm4.85-61.69v51.87l33.95-25.94zM249.54 431.7v-20.8h14.26v3.52h-10.06v4.92h8.68v3.52h-8.68v8.84zM271.94 431.7v-17.29h-6.17v-3.52h16.53v3.52h-6.16v17.29zM285 431.7v-20.8h6.74q3.83 0 4.99.31a5.4 5.4 0 0 1 2.99 2.04 6.5 6.5 0 0 1 1.21 4.05 7 7 0 0 1-.7 3.22 6.06 6.06 0 0 1-3.95 3.04q-1.5.3-4.35.3h-2.74v7.85H285Zm4.2-17.28v5.9h2.3q2.48 0 3.32-.33a2.7 2.7 0 0 0 1.79-2.64q0-1.14-.67-1.87a3 3 0 0 0-1.69-.92q-.75-.14-3.02-.14z"/></g></>
    ) },
    "it": { kind: "vector", body: (_ns: (localId: string) => string) => (
      <><g transform="translate(5 26.7382) scale(.58264) translate(-221.3 -381.02)"><path fill="#FFFFFF" d="M373.35 383.44 373.35 458.44 223.73 458.44 223.73 383.44z"/><path fill="#0000FF" d="M375.77 460.87H221.3v-79.85h154.47Zm-149.61-4.85h144.76v-70.14H226.16Z"/><path fill="#FFFFFF" d="M367.12 421.14 326.74 451.98 326.74 390.29z"/><path fill="#0000FF" d="M324.32 456.89v-71.52l46.8 35.76zm4.85-61.69v51.87l33.95-25.94zM275.32 430.82h-4.57l-1.82-4.73h-8.31l-1.72 4.73h-4.45l8.1-20.81H267Zm-7.73-8.23-2.87-7.72-2.81 7.72zM277.57 410.02h8.31q2.47 0 3.68.21a5.4 5.4 0 0 1 3.77 2.6q.64 1.09.64 2.43a4.93 4.93 0 0 1-2.92 4.51q1.9.56 2.92 1.89a5 5 0 0 1 1.02 3.14 6.2 6.2 0 0 1-2.46 4.9q-1.14.8-2.82.99-1.05.12-5.06.14h-7.08zm4.19 3.46v4.81h2.75q2.45 0 3.05-.07a2.8 2.8 0 0 0 1.7-.75q.62-.62.62-1.62 0-.96-.53-1.57-.53-.6-1.58-.73a48 48 0 0 0-3.59-.07zm0 8.27v5.56h3.89q2.26 0 2.88-.13a2.6 2.6 0 0 0 1.52-.83q.59-.66.59-1.77 0-.93-.45-1.59a2.6 2.6 0 0 0-1.31-.95q-.85-.3-3.72-.3z"/></g></>
    ) }
  },
};
