// @generated by packages/pipeline/src/gen-react.ts — do not edit manually
import type { BabsIconDefinition } from "./types.js";
import { babs1101 } from "./icons/1101.js";
import { babs1102 } from "./icons/1102.js";
import { babs1103 } from "./icons/1103.js";
import { babs1104 } from "./icons/1104.js";
import { babs1105a } from "./icons/1105a.js";
import { babs1105b } from "./icons/1105b.js";
import { babs1106a } from "./icons/1106a.js";
import { babs1106b } from "./icons/1106b.js";
import { babs1107a } from "./icons/1107a.js";
import { babs1107b } from "./icons/1107b.js";
import { babs1108 } from "./icons/1108.js";
import { babs1109 } from "./icons/1109.js";
import { babs1110 } from "./icons/1110.js";
import { babs1111a } from "./icons/1111a.js";
import { babs1111b } from "./icons/1111b.js";
import { babs1112 } from "./icons/1112.js";
import { babs1113 } from "./icons/1113.js";
import { babs1114 } from "./icons/1114.js";
import { babs1115 } from "./icons/1115.js";
import { babs1116a } from "./icons/1116a.js";
import { babs1116b } from "./icons/1116b.js";
import { babs1201 } from "./icons/1201.js";
import { babs1202 } from "./icons/1202.js";
import { babs1203 } from "./icons/1203.js";
import { babs1301 } from "./icons/1301.js";
import { babs1302 } from "./icons/1302.js";
import { babs1303 } from "./icons/1303.js";
import { babs1304 } from "./icons/1304.js";
import { babs1305 } from "./icons/1305.js";
import { babs1401 } from "./icons/1401.js";
import { babs1401a } from "./icons/1401a.js";
import { babs1401b } from "./icons/1401b.js";
import { babs1402 } from "./icons/1402.js";
import { babs1403 } from "./icons/1403.js";
import { babs1403b } from "./icons/1403b.js";
import { babs1404 } from "./icons/1404.js";
import { babs2101 } from "./icons/2101.js";
import { babs2102 } from "./icons/2102.js";
import { babs2103 } from "./icons/2103.js";
import { babs2104 } from "./icons/2104.js";
import { babs2105 } from "./icons/2105.js";
import { babs2106 } from "./icons/2106.js";
import { babs2107 } from "./icons/2107.js";
import { babs2108 } from "./icons/2108.js";
import { babs2109a } from "./icons/2109a.js";
import { babs2109b } from "./icons/2109b.js";
import { babs3101 } from "./icons/3101.js";
import { babs3102 } from "./icons/3102.js";
import { babs3103 } from "./icons/3103.js";
import { babs3104 } from "./icons/3104.js";
import { babs3105 } from "./icons/3105.js";
import { babs3106 } from "./icons/3106.js";
import { babs3107 } from "./icons/3107.js";
import { babs3108 } from "./icons/3108.js";
import { babs3109 } from "./icons/3109.js";
import { babs3110 } from "./icons/3110.js";
import { babs4101 } from "./icons/4101.js";
import { babs4102 } from "./icons/4102.js";
import { babs4103 } from "./icons/4103.js";
import { babs4104 } from "./icons/4104.js";
import { babs4105 } from "./icons/4105.js";
import { babs4106 } from "./icons/4106.js";
import { babs4107 } from "./icons/4107.js";
import { babs4108 } from "./icons/4108.js";
import { babs4201 } from "./icons/4201.js";
import { babs4202 } from "./icons/4202.js";
import { babs4203 } from "./icons/4203.js";
import { babs4204 } from "./icons/4204.js";
import { babs4205 } from "./icons/4205.js";
import { babs4206 } from "./icons/4206.js";
import { babs4207 } from "./icons/4207.js";
import { babs4208 } from "./icons/4208.js";
import { babs4301 } from "./icons/4301.js";
import { babs4302 } from "./icons/4302.js";
import { babs4303 } from "./icons/4303.js";
import { babs4304 } from "./icons/4304.js";
import { babs4305 } from "./icons/4305.js";
import { babs4306 } from "./icons/4306.js";
import { babs4307 } from "./icons/4307.js";
import { babs4308 } from "./icons/4308.js";
import { babs4401 } from "./icons/4401.js";
import { babs4402 } from "./icons/4402.js";
import { babs4403 } from "./icons/4403.js";
import { babs4404 } from "./icons/4404.js";
import { babs4405 } from "./icons/4405.js";
import { babs4406 } from "./icons/4406.js";
import { babs4407 } from "./icons/4407.js";
import { babs4408 } from "./icons/4408.js";
import { babs4501 } from "./icons/4501.js";
import { babs4502 } from "./icons/4502.js";
import { babs4503 } from "./icons/4503.js";
import { babs4504 } from "./icons/4504.js";
import { babs4505 } from "./icons/4505.js";
import { babs4506 } from "./icons/4506.js";
import { babs4507 } from "./icons/4507.js";
import { babs4508 } from "./icons/4508.js";
import { babs4601 } from "./icons/4601.js";
import { babs4602 } from "./icons/4602.js";
import { babs4603 } from "./icons/4603.js";
import { babs4604 } from "./icons/4604.js";
import { babs4605 } from "./icons/4605.js";
import { babs4606 } from "./icons/4606.js";
import { babs4607 } from "./icons/4607.js";
import { babs4608 } from "./icons/4608.js";
import { babs4701 } from "./icons/4701.js";
import { babs4702 } from "./icons/4702.js";
import { babs4703 } from "./icons/4703.js";
import { babs4704 } from "./icons/4704.js";
import { babs4705 } from "./icons/4705.js";
import { babs4706 } from "./icons/4706.js";
import { babs4801 } from "./icons/4801.js";
import { babs4802 } from "./icons/4802.js";
import { babs4803 } from "./icons/4803.js";
import { babs4804 } from "./icons/4804.js";
import { babs4805 } from "./icons/4805.js";
import { babs4806 } from "./icons/4806.js";
import { babs4807 } from "./icons/4807.js";
import { babs4808 } from "./icons/4808.js";
import { babs5101 } from "./icons/5101.js";
import { babs5102 } from "./icons/5102.js";
import { babs5103 } from "./icons/5103.js";
import { babs5104 } from "./icons/5104.js";
import { babs5105 } from "./icons/5105.js";
import { babs5106 } from "./icons/5106.js";
import { babs5107 } from "./icons/5107.js";
import { babs5108 } from "./icons/5108.js";
import { babs5109 } from "./icons/5109.js";
import { babs5110 } from "./icons/5110.js";
import { babs5111 } from "./icons/5111.js";
import { babs5112 } from "./icons/5112.js";
import { babs5113 } from "./icons/5113.js";
import { babs5114 } from "./icons/5114.js";
import { babs5115 } from "./icons/5115.js";
import { babs5116 } from "./icons/5116.js";
import { babs5117 } from "./icons/5117.js";
import { babs5118 } from "./icons/5118.js";
import { babs5119 } from "./icons/5119.js";
import { babs5120 } from "./icons/5120.js";
import { babs5121 } from "./icons/5121.js";
import { babs5122 } from "./icons/5122.js";
import { babs5123 } from "./icons/5123.js";
import { babs5124 } from "./icons/5124.js";
import { babs5125 } from "./icons/5125.js";
import { babs5126 } from "./icons/5126.js";
import { babs5127 } from "./icons/5127.js";
import { babs5128 } from "./icons/5128.js";
import { babs5129 } from "./icons/5129.js";
import { babs5130 } from "./icons/5130.js";
import { babs5131 } from "./icons/5131.js";
import { babs5132a } from "./icons/5132a.js";
import { babs5132b } from "./icons/5132b.js";
import { babs5133 } from "./icons/5133.js";
import { babs5134 } from "./icons/5134.js";
import { babs5135 } from "./icons/5135.js";
import { babs5136 } from "./icons/5136.js";
import { babs5137 } from "./icons/5137.js";
import { babs6101a } from "./icons/6101a.js";
import { babs6101b } from "./icons/6101b.js";
import { babs6102a } from "./icons/6102a.js";
import { babs6102b } from "./icons/6102b.js";
import { babs6103a } from "./icons/6103a.js";
import { babs6103b } from "./icons/6103b.js";
import { babs6104 } from "./icons/6104.js";
import { babs6105 } from "./icons/6105.js";
import { babs6106 } from "./icons/6106.js";
import { babs6107 } from "./icons/6107.js";
import { babs6108 } from "./icons/6108.js";
import { babs7101 } from "./icons/7101.js";
import { babs7102 } from "./icons/7102.js";
import { babs7103 } from "./icons/7103.js";
import { babs7104 } from "./icons/7104.js";
import { babs7105 } from "./icons/7105.js";
import { babs7106 } from "./icons/7106.js";
import { babs7107 } from "./icons/7107.js";
import { babs7108 } from "./icons/7108.js";
import { babs7109 } from "./icons/7109.js";
import { babs7110 } from "./icons/7110.js";
import { babs7111 } from "./icons/7111.js";
import { babs7112 } from "./icons/7112.js";
import { babs7113 } from "./icons/7113.js";
import { babs7114 } from "./icons/7114.js";
import { babs7115 } from "./icons/7115.js";
import { babs7116 } from "./icons/7116.js";
import { babs7117 } from "./icons/7117.js";
import { babs7118 } from "./icons/7118.js";
import { babs7119 } from "./icons/7119.js";
import { babs8101 } from "./icons/8101.js";
import { babs8102 } from "./icons/8102.js";
import { babs8103 } from "./icons/8103.js";
import { babs8104 } from "./icons/8104.js";
import { babs8105 } from "./icons/8105.js";
import { babs8106 } from "./icons/8106.js";
import { babs8107 } from "./icons/8107.js";
import { babs8108 } from "./icons/8108.js";
import { babs8109 } from "./icons/8109.js";
import { babs8110 } from "./icons/8110.js";
import { babs8111 } from "./icons/8111.js";
import { babs8112 } from "./icons/8112.js";
import { babs8113 } from "./icons/8113.js";
import { babs8201 } from "./icons/8201.js";
import { babs8202 } from "./icons/8202.js";
import { babs8203 } from "./icons/8203.js";
import { babs8204 } from "./icons/8204.js";
import { babs8205 } from "./icons/8205.js";
import { babs8206 } from "./icons/8206.js";
import { babs8207 } from "./icons/8207.js";
import { babs8208 } from "./icons/8208.js";
import { babs8209 } from "./icons/8209.js";
import { babs8210 } from "./icons/8210.js";
import { babs8211 } from "./icons/8211.js";
import { babs8212 } from "./icons/8212.js";
import { babs8213 } from "./icons/8213.js";
import { babs8214 } from "./icons/8214.js";
import { babs8215 } from "./icons/8215.js";
import { babs8216 } from "./icons/8216.js";
import { babs8217 } from "./icons/8217.js";
import { babs8218 } from "./icons/8218.js";
import { babs8219 } from "./icons/8219.js";
import { babs8220 } from "./icons/8220.js";
import { babs8221 } from "./icons/8221.js";
import { babs8222 } from "./icons/8222.js";
import { babs8301 } from "./icons/8301.js";
import { babs8302 } from "./icons/8302.js";
import { babs8303 } from "./icons/8303.js";
import { babs8304 } from "./icons/8304.js";
import { babs8305 } from "./icons/8305.js";
import { babs8306 } from "./icons/8306.js";
import { babs8307 } from "./icons/8307.js";
import { babs8308 } from "./icons/8308.js";
import { babs8309 } from "./icons/8309.js";
import { babs8310 } from "./icons/8310.js";
import { babs8311 } from "./icons/8311.js";
import { babs8312 } from "./icons/8312.js";
import { babs8313 } from "./icons/8313.js";
import { babs8314 } from "./icons/8314.js";
import { babs8315 } from "./icons/8315.js";
import { babs8316 } from "./icons/8316.js";
import { babs8317 } from "./icons/8317.js";
import { babs8318 } from "./icons/8318.js";
import { babs8319 } from "./icons/8319.js";
import { babs8320 } from "./icons/8320.js";
import { babs8321 } from "./icons/8321.js";
import { babs8322 } from "./icons/8322.js";
import { babs8323 } from "./icons/8323.js";
import { babs8324 } from "./icons/8324.js";
import { babs8325 } from "./icons/8325.js";
import { babs8326 } from "./icons/8326.js";
import { babs8327 } from "./icons/8327.js";
import { babs8328 } from "./icons/8328.js";
import { babs8329 } from "./icons/8329.js";
import { babs8330 } from "./icons/8330.js";
import { babs8331 } from "./icons/8331.js";
import { babs8332 } from "./icons/8332.js";
import { babs8333 } from "./icons/8333.js";
import { babs9101a } from "./icons/9101a.js";
import { babs9101b } from "./icons/9101b.js";
import { babs9101c } from "./icons/9101c.js";
import { babs9101d } from "./icons/9101d.js";
import { babs9102 } from "./icons/9102.js";
import { babs9103 } from "./icons/9103.js";
import { babs9104 } from "./icons/9104.js";

const all: readonly BabsIconDefinition[] = [
  babs1101,
  babs1102,
  babs1103,
  babs1104,
  babs1105a,
  babs1105b,
  babs1106a,
  babs1106b,
  babs1107a,
  babs1107b,
  babs1108,
  babs1109,
  babs1110,
  babs1111a,
  babs1111b,
  babs1112,
  babs1113,
  babs1114,
  babs1115,
  babs1116a,
  babs1116b,
  babs1201,
  babs1202,
  babs1203,
  babs1301,
  babs1302,
  babs1303,
  babs1304,
  babs1305,
  babs1401,
  babs1401a,
  babs1401b,
  babs1402,
  babs1403,
  babs1403b,
  babs1404,
  babs2101,
  babs2102,
  babs2103,
  babs2104,
  babs2105,
  babs2106,
  babs2107,
  babs2108,
  babs2109a,
  babs2109b,
  babs3101,
  babs3102,
  babs3103,
  babs3104,
  babs3105,
  babs3106,
  babs3107,
  babs3108,
  babs3109,
  babs3110,
  babs4101,
  babs4102,
  babs4103,
  babs4104,
  babs4105,
  babs4106,
  babs4107,
  babs4108,
  babs4201,
  babs4202,
  babs4203,
  babs4204,
  babs4205,
  babs4206,
  babs4207,
  babs4208,
  babs4301,
  babs4302,
  babs4303,
  babs4304,
  babs4305,
  babs4306,
  babs4307,
  babs4308,
  babs4401,
  babs4402,
  babs4403,
  babs4404,
  babs4405,
  babs4406,
  babs4407,
  babs4408,
  babs4501,
  babs4502,
  babs4503,
  babs4504,
  babs4505,
  babs4506,
  babs4507,
  babs4508,
  babs4601,
  babs4602,
  babs4603,
  babs4604,
  babs4605,
  babs4606,
  babs4607,
  babs4608,
  babs4701,
  babs4702,
  babs4703,
  babs4704,
  babs4705,
  babs4706,
  babs4801,
  babs4802,
  babs4803,
  babs4804,
  babs4805,
  babs4806,
  babs4807,
  babs4808,
  babs5101,
  babs5102,
  babs5103,
  babs5104,
  babs5105,
  babs5106,
  babs5107,
  babs5108,
  babs5109,
  babs5110,
  babs5111,
  babs5112,
  babs5113,
  babs5114,
  babs5115,
  babs5116,
  babs5117,
  babs5118,
  babs5119,
  babs5120,
  babs5121,
  babs5122,
  babs5123,
  babs5124,
  babs5125,
  babs5126,
  babs5127,
  babs5128,
  babs5129,
  babs5130,
  babs5131,
  babs5132a,
  babs5132b,
  babs5133,
  babs5134,
  babs5135,
  babs5136,
  babs5137,
  babs6101a,
  babs6101b,
  babs6102a,
  babs6102b,
  babs6103a,
  babs6103b,
  babs6104,
  babs6105,
  babs6106,
  babs6107,
  babs6108,
  babs7101,
  babs7102,
  babs7103,
  babs7104,
  babs7105,
  babs7106,
  babs7107,
  babs7108,
  babs7109,
  babs7110,
  babs7111,
  babs7112,
  babs7113,
  babs7114,
  babs7115,
  babs7116,
  babs7117,
  babs7118,
  babs7119,
  babs8101,
  babs8102,
  babs8103,
  babs8104,
  babs8105,
  babs8106,
  babs8107,
  babs8108,
  babs8109,
  babs8110,
  babs8111,
  babs8112,
  babs8113,
  babs8201,
  babs8202,
  babs8203,
  babs8204,
  babs8205,
  babs8206,
  babs8207,
  babs8208,
  babs8209,
  babs8210,
  babs8211,
  babs8212,
  babs8213,
  babs8214,
  babs8215,
  babs8216,
  babs8217,
  babs8218,
  babs8219,
  babs8220,
  babs8221,
  babs8222,
  babs8301,
  babs8302,
  babs8303,
  babs8304,
  babs8305,
  babs8306,
  babs8307,
  babs8308,
  babs8309,
  babs8310,
  babs8311,
  babs8312,
  babs8313,
  babs8314,
  babs8315,
  babs8316,
  babs8317,
  babs8318,
  babs8319,
  babs8320,
  babs8321,
  babs8322,
  babs8323,
  babs8324,
  babs8325,
  babs8326,
  babs8327,
  babs8328,
  babs8329,
  babs8330,
  babs8331,
  babs8332,
  babs8333,
  babs9101a,
  babs9101b,
  babs9101c,
  babs9101d,
  babs9102,
  babs9103,
  babs9104,
];
export default all;
